import {
  Banknote,
  BarChart3,
  Briefcase,
  MessageSquare,
  Truck,
  TrendingUp,
  FileText,
  Calculator,
  ShieldCheck,
  PiggyBank,
  LucideIcon,
} from "lucide-react";

export interface LevelItem {
  id: string;
  disciplineId: number;
  disciplineName: string;
  slug: string;
  icon: LucideIcon;
  color: string;
  themeLinear: string;
  bgLight: string;
  title: string;
  focus: string;
  example: string;
  practicalAction: string;
}

export interface LevelCategory {
  id: number;
  levelNumber: number;
  name: string;
  subtitle: string;
  description: string;
  tagline: string;
  badge: string;
}

export const VALUE_TREATED_LEVELS: LevelCategory[] = [
  {
    id: 1,
    levelNumber: 1,
    name: "Fondasi & Instrumen Pokok",
    subtitle: "Pilar 1 — Foundation & Core Instruments",
    tagline: "Mengenal instrumen primer penentu nilai dari setiap disiplin ilmu",
    description: "Tingkat dasar yang memetakan satuan unit nilai, data input awal, dan instrumen kepemilikan paling fundamental sebelum masuk ke transaksi.",
    badge: "Level 1: Fondasi",
  },
  {
    id: 2,
    levelNumber: 2,
    name: "Mekanisme & Alur Pertukaran",
    subtitle: "Pilar 2 — Mechanisms & Flow Architecture",
    tagline: "Merancang tata cara pertukaran nilai, pengolahan sistem, dan validasi solusi",
    description: "Tingkat proses yang mengatur bagaimana instrumen bertukar tangan, aturan main pertukaran, pemrosesan data, dan standarisasi operasional.",
    badge: "Level 2: Mekanisme",
  },
  {
    id: 3,
    levelNumber: 3,
    name: "Perputaran & Dinamika Eksekusi",
    subtitle: "Pilar 3 — Velocity & Execution Operations",
    tagline: "Mengakselerasi kecepatan arus kas, barang, informasi, dan perputaran modal",
    description: "Tingkat dinamika yang mengukur kecepatan transmisi (velocity), manajemen waktu, pengelolaan gudang, dan pelaporan perputaran berkala.",
    badge: "Level 3: Perputaran",
  },
  {
    id: 4,
    levelNumber: 4,
    name: "Kelangkaan, Alokasi & Keputusan",
    subtitle: "Pilar 4 — Constraints, Allocation & Strategy",
    tagline: "Mengoptimalkan batas keterbatasan modal, waktu, dan risiko untuk laba maksimal",
    description: "Tingkat strategis di mana keputusan alokasi sumber daya langka diambil untuk mencapai profitabilitas, proteksi klaim, dan return investasi puncak.",
    badge: "Level 4: Alokasi & Keputusan",
  },
];

export const DISCIPLINE_LEVEL_DATA: Record<number, LevelItem[]> = {
  // LEVEL 1: Fondasi & Instrumen Pokok
  1: [
    {
      id: "l1-eko",
      disciplineId: 1,
      disciplineName: "Ekonomi",
      slug: "ekonomi",
      icon: Banknote,
      color: "text-emerald-500",
      themeLinear: "from-emerald-500 to-teal-700",
      bgLight: "bg-emerald-500/10 border-emerald-500/30",
      title: "Uang & Nilai Nominal",
      focus: "Evolusi dan fungsi uang sebagai alat tukar sah, satuan hitung akurat, dan penyimpan nilai resmi dalam perekonomian.",
      example: "Uang fiat beredar, sistem kliring perbankan, dan likuiditas moneter (M1/M2).",
      practicalAction: "Audit likuiditas kas operasional usaha mingguan.",
    },
    {
      id: "l1-stat",
      disciplineId: 2,
      disciplineName: "Statistik",
      slug: "statistik",
      icon: BarChart3,
      color: "text-blue-500",
      themeLinear: "from-blue-500 to-indigo-700",
      bgLight: "bg-blue-500/10 border-blue-500/30",
      title: "Data & Variabel Pokok",
      focus: "Pengenalan jenis data kuantitatif vs kualitatif, skala pengukuran (nominal, ordinal, rasio), dan integritas sumber input.",
      example: "Pencatatan data transaksi harian, umur pelanggan, dan rating kepuasan layanan.",
      practicalAction: "Pembersihan dataset mentah (data cleansing) dari input ganda.",
    },
    {
      id: "l1-man",
      disciplineId: 3,
      disciplineName: "Manajemen",
      slug: "manajemen",
      icon: Briefcase,
      color: "text-purple-500",
      themeLinear: "from-purple-500 to-violet-700",
      bgLight: "bg-purple-500/10 border-purple-500/30",
      title: "Manajemen Diri (Self-Management)",
      focus: "Fondasi kepemimpinan personal, alokasi energi kerja, penetapan integritas, dan penguasaan kebiasaan produktif harian.",
      example: "Audit kebiasaan kerja eksekutif, pembatasan distraksi, dan self-regulation.",
      practicalAction: "Menyusun jadwal blok fokus harian 90 menit tanpa distraksi.",
    },
    {
      id: "l1-kom",
      disciplineId: 4,
      disciplineName: "Komunikasi",
      slug: "komunikasi",
      icon: MessageSquare,
      color: "text-rose-500",
      themeLinear: "from-rose-500 to-pink-700",
      bgLight: "bg-rose-500/10 border-rose-500/30",
      title: "Komunikasi Dasar & Intensi",
      focus: "Elemen dasar transmisi gagasan: komunikator, pesan verbal/visual, media transmisi, komunikan, dan eliminasi gangguan (noise).",
      example: "Penyampaian arahan kerja pagi (briefing) secara ringkas, tegas, dan satu arah.",
      practicalAction: "Format penulisan pesan 3 kalimat: Konteks - Inti Masalah - Tindakan.",
    },
    {
      id: "l1-log",
      disciplineId: 5,
      disciplineName: "Logistik",
      slug: "logistik",
      icon: Truck,
      color: "text-cyan-500",
      themeLinear: "from-cyan-500 to-blue-700",
      bgLight: "bg-cyan-500/10 border-cyan-500/30",
      title: "Prinsip 5T Logistik",
      focus: "Standar pemenuhan rantai nilai: Tepat Barang, Tepat Jumlah, Tepat Waktu, Tepat Tempat, dan Tepat Biaya.",
      example: "Pencapaian On-Time In-Full (OTIF) 98% pengiriman barang konsumsi.",
      practicalAction: "Pembuatan checklist serah-terima muatan kurir berbasis 5T.",
    },
    {
      id: "l1-bis",
      disciplineId: 6,
      disciplineName: "Bisnis",
      slug: "bisnis",
      icon: TrendingUp,
      color: "text-amber-500",
      themeLinear: "from-amber-500 to-orange-700",
      bgLight: "bg-amber-500/10 border-amber-500/30",
      title: "Jual-Beli & Penciptaan Nilai",
      focus: "Hakikat komersial: proses pertukaran kepemilikan bernilai tambah yang saling menguntungkan antara penjual dan pembeli.",
      example: "Penetapan margin kotor (gross margin) atas produk olahan yang bernilai fungsi tinggi.",
      practicalAction: "Menghitung selisih harga pokok produksi dengan nilai kesediaan bayar.",
    },
    {
      id: "l1-adm",
      disciplineId: 7,
      disciplineName: "Administrasi",
      slug: "administrasi",
      icon: FileText,
      color: "text-slate-500",
      themeLinear: "from-slate-500 to-gray-700",
      bgLight: "bg-slate-500/10 border-slate-500/30",
      title: "Tata Kelola Dokumen & Legalitas",
      focus: "Standarisasi pencatatan dokumen legal, identitas entitas usaha (NIB, NPWP), dan format surat-menyurat resmi perusahaan.",
      example: "Katalogisasi surat perjanjian kontrak kerja sama dan registrasi legal perizinan.",
      practicalAction: "Penyusunan kode penomoran berkas digital terpadu per departemen.",
    },
    {
      id: "l1-aku",
      disciplineId: 8,
      disciplineName: "Akuntansi",
      slug: "akuntansi",
      icon: Calculator,
      color: "text-indigo-500",
      themeLinear: "from-indigo-500 to-purple-700",
      bgLight: "bg-indigo-500/10 border-indigo-500/30",
      title: "Persamaan Dasar Akuntansi",
      focus: "Prinsip keseimbangan universal: Aset = Liabilitas + Ekuitas, serta penegakan batas entitas bisnis terpisah dari pemilik.",
      example: "Pemisahan mutlak rekening kas pribadi pemilik modal dengan rekening operasional usaha.",
      practicalAction: "Pencatatan saldo modal disetor awal dan saldo kas pada buku kas bank.",
    },
    {
      id: "l1-asu",
      disciplineId: 9,
      disciplineName: "Asuransi",
      slug: "asuransi",
      icon: ShieldCheck,
      color: "text-teal-500",
      themeLinear: "from-teal-500 to-emerald-700",
      bgLight: "bg-teal-500/10 border-teal-500/30",
      title: "Proteksi Risiko Murni (Pure Risk)",
      focus: "Identifikasi potensi kerugian tak terduga yang bersifat murni (rusak, hilang, musibah) yang dapat mengancam kelangsungan usaha.",
      example: "Proteksi risiko kebakaran gudang pabrik dan kecelakaan armada kendaraan distribusi.",
      practicalAction: "Penyusunan peta risiko aset fisik (risk register) terhadap potensi bahaya.",
    },
    {
      id: "l1-inv",
      disciplineId: 10,
      disciplineName: "Investasi",
      slug: "investasi",
      icon: PiggyBank,
      color: "text-yellow-500",
      themeLinear: "from-yellow-500 to-amber-700",
      bgLight: "bg-yellow-500/10 border-yellow-500/30",
      title: "Nilai Waktu Uang (Time Value of Money)",
      focus: "Prinsip bahwa sejumlah uang saat ini lebih bernilai dibandingkan jumlah yang sama di masa depan karena potensi hasil investasi.",
      example: "Kalkulasi Present Value (PV) dan Future Value (FV) arus kas proyek jangka 3 tahun.",
      practicalAction: "Menghitung tingkat diskonto modal (hurdle rate) minimum sebelum ekspansi.",
    },
  ],

  // LEVEL 2: Mekanisme & Alur Pertukaran
  2: [
    {
      id: "l2-eko",
      disciplineId: 1,
      disciplineName: "Ekonomi",
      slug: "ekonomi",
      icon: Banknote,
      color: "text-emerald-500",
      themeLinear: "from-emerald-500 to-teal-700",
      bgLight: "bg-emerald-500/10 border-emerald-500/30",
      title: "Mekanisme Pasar & Harga Ekuilibrium",
      focus: "Interaksi dinamis penawaran produsen dan permintaan konsumen yang membentuk titik temu harga wajar tanpa distorsi.",
      example: "Penyesuaian otomatis harga beras dan komoditas bahan pokok saat panen raya vs paceklik.",
      practicalAction: "Analisis elastisitas harga permintaan saat menguji kenaikan harga produk.",
    },
    {
      id: "l2-stat",
      disciplineId: 2,
      disciplineName: "Statistik",
      slug: "statistik",
      icon: BarChart3,
      color: "text-blue-500",
      themeLinear: "from-blue-500 to-indigo-700",
      bgLight: "bg-blue-500/10 border-blue-500/30",
      title: "Sampling & Pemrosesan Big Data",
      focus: "Metodologi penarikan sampel acak representatif dan teknik pengelompokan data dalam volume besar untuk menghindari bias seleksi.",
      example: "Pengambilan sampel acak bertingkat (stratified sampling) preferensi konsumen di 5 kota besar.",
      practicalAction: "Menentukan batas ukuran sampel minimum menggunakan rumus Slovin.",
    },
    {
      id: "l2-man",
      disciplineId: 3,
      disciplineName: "Manajemen",
      slug: "manajemen",
      icon: Briefcase,
      color: "text-purple-500",
      themeLinear: "from-purple-500 to-violet-700",
      bgLight: "bg-purple-500/10 border-purple-500/30",
      title: "Matriks Prioritas Eisenhower",
      focus: "Kerangka klasifikasi keputusan berdasarkan derajat kepentingan strategis (Importance) vs tingkat keterdesakan waktu (Urgency).",
      example: "Memisahkan tugas krisis mendesak di Kuadran I dari aktivitas perencanaan strategis di Kuadran II.",
      practicalAction: "Mendelegasikan 100% tugas Kuadran III (Mendesak tapi Tidak Penting) ke tim pendukung.",
    },
    {
      id: "l2-kom",
      disciplineId: 4,
      disciplineName: "Komunikasi",
      slug: "komunikasi",
      icon: MessageSquare,
      color: "text-rose-500",
      themeLinear: "from-rose-500 to-pink-700",
      bgLight: "bg-rose-500/10 border-rose-500/30",
      title: "Model Transmisi Shannon-Weaver",
      focus: "Rekayasa encoding pesan tertulis, pemilihan saluran transmisi yang minim distorsi, dan proses decoding oleh penerima.",
      example: "Standardisasi penulisan memo instruksi kerja dan pengumuman operasional lintas divisi.",
      practicalAction: "Uji keterbacaan pesan melalui konfirmasi pemahaman 'read-back' dari penerima.",
    },
    {
      id: "l2-log",
      disciplineId: 5,
      disciplineName: "Logistik",
      slug: "logistik",
      icon: Truck,
      color: "text-cyan-500",
      themeLinear: "from-cyan-500 to-blue-700",
      bgLight: "bg-cyan-500/10 border-cyan-500/30",
      title: "Arsitektur Rantai Pasok (Supply Chain)",
      focus: "Sinkronisasi arus material, arus informasi, dan arus kas dari pemasok lapis pertama hingga konsumen akhir.",
      example: "Penyelarasan jadwal pasokan bahan baku dari petani dengan kapasitas giling pabrik pengolahan.",
      practicalAction: "Pemetaan alur pasok (Value Stream Mapping) guna memotong titik tunggu pesanan.",
    },
    {
      id: "l2-bis",
      disciplineId: 6,
      disciplineName: "Bisnis",
      slug: "bisnis",
      icon: TrendingUp,
      color: "text-amber-500",
      themeLinear: "from-amber-500 to-orange-700",
      bgLight: "bg-amber-500/10 border-amber-500/30",
      title: "Desain Produk & Kesesuaian Solusi",
      focus: "Penyusunan portofolio produk atau paket layanan bernilai tambah yang menyelesaikan problem utama audiens (Problem-Solution Fit).",
      example: "Pengembangan Minimum Viable Product (MVP) dengan fitur inti untuk validasi pasar awal.",
      practicalAction: "Menjalankan uji kesesuaian produk terhadap 20 calon pelanggan perintis.",
    },
    {
      id: "l2-adm",
      disciplineId: 7,
      disciplineName: "Administrasi",
      slug: "administrasi",
      icon: FileText,
      color: "text-slate-500",
      themeLinear: "from-slate-500 to-gray-700",
      bgLight: "bg-slate-500/10 border-slate-500/30",
      title: "Standar Operasional Prosedur (SOP)",
      focus: "Penyusunan pedoman alur kerja tertulis, batas waktu eksekusi, penanggung jawab tugas, dan kriteria keberhasilan mutu kerja.",
      example: "SOP penerimaan barang masuk ke gudang lengkap dengan inspeksi kualitas dan verifikasi surat jalan.",
      practicalAction: "Dokumentasi flowchart langkah demi langkah untuk setiap aktivitas repetitif.",
    },
    {
      id: "l2-aku",
      disciplineId: 8,
      disciplineName: "Akuntansi",
      slug: "akuntansi",
      icon: Calculator,
      color: "text-indigo-500",
      themeLinear: "from-indigo-500 to-purple-700",
      bgLight: "bg-indigo-500/10 border-indigo-500/30",
      title: "Sistem Debit-Kredit Berpasangan",
      focus: "Penerapan kaidah double-entry di mana setiap transaksi selalu mencatat pertambahan di satu sisi dan pengurangan di sisi lain.",
      example: "Pembelian mesin produksi tunai: Kas berkurang di Kredit, Akun Peralatan bertambah di Debit.",
      practicalAction: "Verifikasi keseimbangan total saldo debit dan total saldo kredit setiap akhir pekan.",
    },
    {
      id: "l2-asu",
      disciplineId: 9,
      disciplineName: "Asuransi",
      slug: "asuransi",
      icon: ShieldCheck,
      color: "text-teal-500",
      themeLinear: "from-teal-500 to-emerald-700",
      bgLight: "bg-teal-500/10 border-teal-500/30",
      title: "Kontrak Polis & Klausul Perlindungan",
      focus: "Dekonstruksi pasal kontrak asuransi: batasan pertanggungan, pengecualian klaim, deduktibel (own risk), dan periode masa tunggu.",
      example: "Penerapan polis Marine Cargo All Risks untuk perlindungan kontainer selama pelayaran antar pulau.",
      practicalAction: "Audit klausul pengecualian dalam polis agar tidak terjadi penolakan klaim saat klaim diajukan.",
    },
    {
      id: "l2-inv",
      disciplineId: 10,
      disciplineName: "Investasi",
      slug: "investasi",
      icon: PiggyBank,
      color: "text-yellow-500",
      themeLinear: "from-yellow-500 to-amber-700",
      bgLight: "bg-yellow-500/10 border-yellow-500/30",
      title: "Penggandaan Bunga Majemuk",
      focus: "Eksploitasi rumus eksponensial bunga berbunga (compounding effect) di mana return diinvestasikan kembali untuk melipatgandakan aset.",
      example: "Simulasi modal awal 100 juta dengan return majemuk 12% per tahun bertumbuh menjadi 310 juta dalam 10 tahun.",
      practicalAction: "Menerapkan kebijakan reinvestasi 80% dividen hasil usaha pada instrumen bertumbuh.",
    },
  ],

  // LEVEL 3: Perputaran & Dinamika Eksekusi
  3: [
    {
      id: "l3-eko",
      disciplineId: 1,
      disciplineName: "Ekonomi",
      slug: "ekonomi",
      icon: Banknote,
      color: "text-emerald-500",
      themeLinear: "from-emerald-500 to-teal-700",
      bgLight: "bg-emerald-500/10 border-emerald-500/30",
      title: "Kecepatan Perputaran Uang (Velocity)",
      focus: "Tingkat frekuensi perpindahan uang dari satu pihak ke pihak lain yang memicu ekspansi transaksi riil dan pertumbuhan ekonomi.",
      example: "Tingginya transaksi digital QRIS di ekosistem ritel mempercepat perputaran kas modal kerja UMKM.",
      practicalAction: "Mengukur hari rata-rata perputaran kas operasional dari penjualan tunai harian.",
    },
    {
      id: "l3-stat",
      disciplineId: 2,
      disciplineName: "Statistik",
      slug: "statistik",
      icon: BarChart3,
      color: "text-blue-500",
      themeLinear: "from-blue-500 to-indigo-700",
      bgLight: "bg-blue-500/10 border-blue-500/30",
      title: "Ukuran Pemusatan & Dispersi Deviasi",
      focus: "Penetapan nilai pusat data (Mean, Median, Modus) serta variasi sebaran nilai (Standar Deviasi) untuk deteksi fluktuasi abnormal.",
      example: "Evaluasi deviasi waktu tunggu pelanggan di restoran cepat saji guna menjaga standar layanan.",
      practicalAction: "Memasang batas kontrol atas dan bawah (Control Chart) pada waktu penyelesaian pesanan.",
    },
    {
      id: "l3-man",
      disciplineId: 3,
      disciplineName: "Manajemen",
      slug: "manajemen",
      icon: Briefcase,
      color: "text-purple-500",
      themeLinear: "from-purple-500 to-violet-700",
      bgLight: "bg-purple-500/10 border-purple-500/30",
      title: "Manajemen Waktu & Time Blocking",
      focus: "Penyusunan blok jadwal harian yang ketat untuk eksekusi prioritas, eliminasi meeting tanpa tujuan, dan proteksi ritme fokus tim.",
      example: "Penerapan 'Focus Friday' di mana tim dilarang mengadakan meeting internal untuk fokus penyelesaian tugas inti.",
      practicalAction: "Membatasi durasi maksimal meeting operasional harian menjadi maksimal 20 menit berdiri.",
    },
    {
      id: "l3-kom",
      disciplineId: 4,
      disciplineName: "Komunikasi",
      slug: "komunikasi",
      icon: MessageSquare,
      color: "text-rose-500",
      themeLinear: "from-rose-500 to-pink-700",
      bgLight: "bg-rose-500/10 border-rose-500/30",
      title: "Kesesuaian Bahasa Tubuh & Struktur Narasi",
      focus: "Penyelarasan intonasi vokal, kontak mata, mikroekspresi, serta struktur piramida narasi dalam negosiasi dan presentasi penawaran.",
      example: "Teknik presentasi pitch deck investor menggunakan alur: Masalah - Solusi - Traksi - Tim - Kebutuhan Dana.",
      practicalAction: "Latihan simulasi negosiasi 3 menit dengan teknik mirroring dan aktif mendengarkan.",
    },
    {
      id: "l3-log",
      disciplineId: 5,
      disciplineName: "Logistik",
      slug: "logistik",
      icon: Truck,
      color: "text-cyan-500",
      themeLinear: "from-cyan-500 to-blue-700",
      bgLight: "bg-cyan-500/10 border-cyan-500/30",
      title: "Tata Kelola Pergudangan & FIFO",
      focus: "Optimasi slotting gudang, sistem First-In First-Out untuk mencegah kedaluwarsa produk, dan kecepatan penyiapan pesanan (picking).",
      example: "Penempatan barang cepat laku (fast-moving) paling dekat dengan pintu muat gudang distribusi.",
      practicalAction: "Audit akurasi stok fisik harian (cycle counting) terhadap catatan sistem gudang.",
    },
    {
      id: "l3-bis",
      disciplineId: 6,
      disciplineName: "Bisnis",
      slug: "bisnis",
      icon: TrendingUp,
      color: "text-amber-500",
      themeLinear: "from-amber-500 to-orange-700",
      bgLight: "bg-amber-500/10 border-amber-500/30",
      title: "Siklus Konversi Kas (Cash Conversion Cycle)",
      focus: "Kecepatan waktu yang dibutuhkan dari sejak kas dikeluarkan untuk membeli bahan baku hingga kas kembali diterima dari pelanggan.",
      example: "Memperpendek hari piutang dagang (DSO) dan memperpanjang hari utang vendor (DPO) secara adil.",
      practicalAction: "Memberikan diskon pelunasan cepat 2/10 net 30 kepada pelanggan utama.",
    },
    {
      id: "l3-adm",
      disciplineId: 7,
      disciplineName: "Administrasi",
      slug: "administrasi",
      icon: FileText,
      color: "text-slate-500",
      themeLinear: "from-slate-500 to-gray-700",
      bgLight: "bg-slate-500/10 border-slate-500/30",
      title: "Pengarsipan Aktif & Retensi Digital",
      focus: "Klasifikasi arsip aktif operasional vs inaktif, sistem proteksi backup berbasis cloud terenkripsi, dan kepatuhan masa retensi dokumen.",
      example: "Penyimpanan otomatis faktur pajak elektronik dan kuitansi pada folder cloud dengan hak akses berjenjang.",
      practicalAction: "Menjalankan pemulihan data uji coba (restore drill) arsip digital setiap kuartal.",
    },
    {
      id: "l3-aku",
      disciplineId: 8,
      disciplineName: "Akuntansi",
      slug: "akuntansi",
      icon: Calculator,
      color: "text-indigo-500",
      themeLinear: "from-indigo-500 to-purple-700",
      bgLight: "bg-indigo-500/10 border-indigo-500/30",
      title: "Posting Jurnal ke Buku Besar",
      focus: "Pencatatan kronologis transaksi ke dalam jurnal umum dan pemindahbukuan sistematis ke masing-masing akun buku besar pembantu.",
      example: "Posting mutasi pembayaran piutang ke sub-ledger buku besar kartu piutang per pelanggan.",
      practicalAction: "Tutup buku jurnal harian maksimal 2 jam setelah kasir toko ditutup.",
    },
    {
      id: "l3-asu",
      disciplineId: 9,
      disciplineName: "Asuransi",
      slug: "asuransi",
      icon: ShieldCheck,
      color: "text-teal-500",
      themeLinear: "from-teal-500 to-emerald-700",
      bgLight: "bg-teal-500/10 border-teal-500/30",
      title: "Struktur Premi & Underwriting",
      focus: "Perhitungan premi asuransi yang adil dan proporsional berdasarkan profil risiko historis dan prinsip hukum bilangan besar (law of large numbers).",
      example: "Penetapan rate premi asuransi kebakaran bangunan dengan sistem sprinkler otomatis lebih murah 30%.",
      practicalAction: "Melakukan mitigasi bahaya fisik di lokasi pabrik untuk menurunkan beban premi tahunan.",
    },
    {
      id: "l3-inv",
      disciplineId: 10,
      disciplineName: "Investasi",
      slug: "investasi",
      icon: PiggyBank,
      color: "text-yellow-500",
      themeLinear: "from-yellow-500 to-amber-700",
      bgLight: "bg-yellow-500/10 border-yellow-500/30",
      title: "Analisis Profil Risiko & Kelas Aset",
      focus: "Pemetaan spektrum imbal hasil vs risiko (risk-reward profile): instrumen pasar uang, pendapatan tetap, ekuitas saham, hingga aset riil.",
      example: "Penentuan batas toleransi penurunan portofolio (drawdown) maksimal 10% untuk kebutuhan dana darurat usaha.",
      practicalAction: "Rebalancing komposisi portofolio setiap 6 bulan agar tetap sesuai profil risiko.",
    },
  ],

  // LEVEL 4: Kelangkaan, Alokasi & Keputusan
  4: [
    {
      id: "l4-eko",
      disciplineId: 1,
      disciplineName: "Ekonomi",
      slug: "ekonomi",
      icon: Banknote,
      color: "text-emerald-500",
      themeLinear: "from-emerald-500 to-teal-700",
      bgLight: "bg-emerald-500/10 border-emerald-500/30",
      title: "Kelangkaan Sumber Daya & Biaya Peluang",
      focus: "Pengambilan keputusan strategis di bawah batasan modal yang terbatas: menimbang manfaat opsi terpilih vs opsi yang dikorbankan (Opportunity Cost).",
      example: "Trade-off antara membuka gerai cabang baru vs mengalokasikan anggaran untuk digital marketing nasional.",
      practicalAction: "Menghitung nilai Net Present Value (NPV) dari dua opsi investasi modal yang bersaing.",
    },
    {
      id: "l4-stat",
      disciplineId: 2,
      disciplineName: "Statistik",
      slug: "statistik",
      icon: BarChart3,
      color: "text-blue-500",
      themeLinear: "from-blue-500 to-indigo-700",
      bgLight: "bg-blue-500/10 border-blue-500/30",
      title: "Uji Hipotesis & Analisis Inferensi",
      focus: "Penarikan kesimpulan ilmiah terhadap populasi dengan tingkat signifikansi statistik (p-value < 0.05) guna memvalidasi efektivitas inovasi.",
      example: "Uji A/B testing desain tombol checkout baru terbukti meningkatkan konversi penjualan sebesar 4.2% secara signifikan.",
      practicalAction: "Mengambil keputusan peluncuran fitur baru hanya jika p-value hasil uji statistik < 0.05.",
    },
    {
      id: "l4-man",
      disciplineId: 3,
      disciplineName: "Manajemen",
      slug: "manajemen",
      icon: Briefcase,
      color: "text-purple-500",
      themeLinear: "from-purple-500 to-violet-700",
      bgLight: "bg-purple-500/10 border-purple-500/30",
      title: "Penetapan Sasaran Berbasis SMART",
      focus: "Perumusan target kerja organisasi yang Specific, Measurable, Achievable, Relevant, dan Time-bound demi akuntabilitas kepemimpinan.",
      example: "Menaikkan retensi pelanggan korporat dari 82% menjadi 90% pada penutupan Q4 melalui program loyalitas khusus.",
      practicalAction: "Membuat scorecard kinerja individu yang selaras dengan target SMART departemen.",
    },
    {
      id: "l4-kom",
      disciplineId: 4,
      disciplineName: "Komunikasi",
      slug: "komunikasi",
      icon: MessageSquare,
      color: "text-rose-500",
      themeLinear: "from-rose-500 to-pink-700",
      bgLight: "bg-rose-500/10 border-rose-500/30",
      title: "Lingkaran Umpan Balik (Feedback Loop)",
      focus: "Pembangunan saluran evaluasi dua arah untuk menampung masukan pelanggan dan tim guna penyempurnaan produk secara berkelanjutan.",
      example: "Sistem Net Promoter Score (NPS) berkala dan penanganan komplain pelanggan dalam waktu < 2 jam.",
      practicalAction: "Menggelar rapat 'Post-Mortem' evaluasi proyek tanpa saling menyalahkan (blameless review).",
    },
    {
      id: "l4-log",
      disciplineId: 5,
      disciplineName: "Logistik",
      slug: "logistik",
      icon: Truck,
      color: "text-cyan-500",
      themeLinear: "from-cyan-500 to-blue-700",
      bgLight: "bg-cyan-500/10 border-cyan-500/30",
      title: "Economic Order Quantity & Safety Stock",
      focus: "Penetapan jumlah pesanan optimal yang meminimalkan total biaya simpan dan biaya pesan, serta penentuan batas stok cadangan aman.",
      example: "Kalkulasi titik pemesanan kembali (Reorder Point) untuk mengantisipasi keterlambatan kirim vendor saat musim hujan.",
      practicalAction: "Menyetel notifikasi otomatis sistem saat stok gudang menyentuh batas safety stock.",
    },
    {
      id: "l4-bis",
      disciplineId: 6,
      disciplineName: "Bisnis",
      slug: "bisnis",
      icon: TrendingUp,
      color: "text-amber-500",
      themeLinear: "from-amber-500 to-orange-700",
      bgLight: "bg-amber-500/10 border-amber-500/30",
      title: "Titik Impas (BEP) & Skalabilitas Profit",
      focus: "Perhitungan volume penjualan minimum untuk menutup seluruh biaya tetap (Fixed Cost), dan strategi ekspansi margin saat skala membesar.",
      example: "Penentuan kuota penjualan 500 unit per bulan sebagai batas impas operasional cabang toko baru.",
      practicalAction: "Menghitung Contribution Margin per unit produk untuk memprioritaskan penjualan produk terlaris.",
    },
    {
      id: "l4-adm",
      disciplineId: 7,
      disciplineName: "Administrasi",
      slug: "administrasi",
      icon: FileText,
      color: "text-slate-500",
      themeLinear: "from-slate-500 to-gray-700",
      bgLight: "bg-slate-500/10 border-slate-500/30",
      title: "Kepatuhan Regulasi & Kesiapan Audit",
      focus: "Penegakan tata kelola usaha yang taat hukum ketenagakerjaan, perpajakan, keselamatan kerja (K3), dan kesiapan menghadapi audit resmi.",
      example: "Kepatuhan pembayaran iuran BPJS Ketenagakerjaan tepat waktu dan kesiapan dokumen bukti potong pajak PPh 21.",
      practicalAction: "Menjalankan mock-audit internal berkala sebelum audit eksternal tahunan berlangsung.",
    },
    {
      id: "l4-aku",
      disciplineId: 8,
      disciplineName: "Akuntansi",
      slug: "akuntansi",
      icon: Calculator,
      color: "text-indigo-500",
      themeLinear: "from-indigo-500 to-purple-700",
      bgLight: "bg-indigo-500/10 border-indigo-500/30",
      title: "Laporan Keuangan & Analisis Rasio",
      focus: "Penyusunan tiga laporan keuangan inti (Neraca, Laba Rugi, Arus Kas) serta analisis rasio likuiditas, solvabilitas, dan profitabilitas.",
      example: "Evaluasi rasio lancar (Current Ratio > 1.5x) untuk menjamin kemampuan pembayaran utang jangka pendek lancar.",
      practicalAction: "Menghitung rasio laba bersih terhadap ekuitas (Return on Equity / ROE) secara berkala.",
    },
    {
      id: "l4-asu",
      disciplineId: 9,
      disciplineName: "Asuransi",
      slug: "asuransi",
      icon: ShieldCheck,
      color: "text-teal-500",
      themeLinear: "from-teal-500 to-emerald-700",
      bgLight: "bg-teal-500/10 border-teal-500/30",
      title: "Penyelesaian Klaim & Asas Indemnitas",
      focus: "Penetapan prinsip ganti rugi (Indemnity) di mana tertanggung dipulihkan ke posisi finansial sebelum terjadi musibah tanpa mengambil untung.",
      example: "Proses verifikasi kerugian klaim asuransi properti pasca banjir dengan laporan loss adjuster independen.",
      practicalAction: "Menyiapkan berkas digital foto dan nota pembelian aset sebagai dokumen pendukung klaim cepat.",
    },
    {
      id: "l4-inv",
      disciplineId: 10,
      disciplineName: "Investasi",
      slug: "investasi",
      icon: PiggyBank,
      color: "text-yellow-500",
      themeLinear: "from-yellow-500 to-amber-700",
      bgLight: "bg-yellow-500/10 border-yellow-500/30",
      title: "Alokasi Modal Portofolio & Diversifikasi",
      focus: "Penyebaran modal lintas instrumen dan industri untuk mengeliminasi risiko tidak sistematis (unsystematic risk) sesuai teori Markowitz.",
      example: "Alokasi portofolio seimbang: 50% reksadana saham bertumbuh, 30% obligasi negara pendapatan tetap, 20% kas likuid.",
      practicalAction: "Menetapkan batasan alokasi modal maksimal 15% pada satu sektor industri tunggal.",
    },
  ],
};
