export type UpdateCadence = 'Harian' | 'Mingguan' | 'Bulanan' | 'Kuartalan' | 'Tahunan';

export type CommodityCategory = 
  | 'Pasar Keuangan & Global'
  | 'Pangan Pokok Lokal'
  | 'Sembako & HET Kemendag'
  | 'Energi & Bahan Bakar'
  | 'Pertanian & Properti Rakyat'
  | 'IHK, Sandang & Material Bangunan'
  | 'Kesehatan & Obat Generik'
  | 'Konsumen & Otomotif'
  | 'Fasilitas Utilitas Publik'
  | 'Tenaga Kerja & Jasa Konstruksi';

export type PricingType = 'Subsidi' | 'HET Pemerintah' | 'Batas Terendah / Floor' | 'Spot Global';

export interface CommodityItem {
  id: number;
  nama: string;
  kategori: CommodityCategory;
  sumberData: string;
  updateCadence: UpdateCadence;
  hargaTerbaru: number;
  mataUang: 'IDR' | 'USD';
  satuan: string;
  jenisBatas: PricingType;
  perubahan24h: number; // percentage
  statusRegulasi: string;
  deskripsiSpesifikasi: string;
  tanggalUpdate: string;
  linkSumber: string;
}

export const COMMODITY_DATA: CommodityItem[] = [
  // 1. TRADINGVIEW / FINANCIAL MARKET API (Global Commodities - Realtime/Harian)
  {
    id: 1,
    nama: "Emas Spot Global (XAU/USD)",
    kategori: "Pasar Keuangan & Global",
    sumberData: "TradingView / Financial Market API",
    updateCadence: "Harian",
    hargaTerbaru: 2578.40,
    mataUang: "USD",
    satuan: "troy oz",
    jenisBatas: "Spot Global",
    perubahan24h: 0.42,
    statusRegulasi: "Bebas Pajak Batangan (PPH 22 Final)",
    deskripsiSpesifikasi: "Kemurnian 99.99% standar LBMA untuk lindung nilai inflasi dan cadangan devisa.",
    tanggalUpdate: "Hari ini",
    linkSumber: "https://www.tradingview.com/markets/commodities/prices/"
  },
  {
    id: 2,
    nama: "Perak Spot Global (XAG/USD)",
    kategori: "Pasar Keuangan & Global",
    sumberData: "TradingView / Financial Market API",
    updateCadence: "Harian",
    hargaTerbaru: 30.65,
    mataUang: "USD",
    satuan: "troy oz",
    jenisBatas: "Spot Global",
    perubahan24h: -0.18,
    statusRegulasi: "Standar Komoditas Industri & Investasi",
    deskripsiSpesifikasi: "Logam perak fisik kemurnian 99.9% untuk komponen sel surya dan sirkuit elektronik.",
    tanggalUpdate: "Hari ini",
    linkSumber: "https://www.tradingview.com/markets/commodities/prices/"
  },
  {
    id: 3,
    nama: "Minyak Mentah Brent",
    kategori: "Pasar Keuangan & Global",
    sumberData: "TradingView / Financial Market API",
    updateCadence: "Harian",
    hargaTerbaru: 73.10,
    mataUang: "USD",
    satuan: "barrel",
    jenisBatas: "Spot Global",
    perubahan24h: 1.15,
    statusRegulasi: "Patokan ICP (Indonesian Crude Price)",
    deskripsiSpesifikasi: "Minyak mentah acuan laut utara, parameter utama subsidi energi APBN.",
    tanggalUpdate: "Hari ini",
    linkSumber: "https://www.tradingview.com/markets/commodities/prices/"
  },
  {
    id: 4,
    nama: "Minyak Mentah WTI",
    kategori: "Pasar Keuangan & Global",
    sumberData: "TradingView / Financial Market API",
    updateCadence: "Harian",
    hargaTerbaru: 69.80,
    mataUang: "USD",
    satuan: "barrel",
    jenisBatas: "Spot Global",
    perubahan24h: 0.95,
    statusRegulasi: "Benchmark Kilang Minyak Internasional",
    deskripsiSpesifikasi: "Light sweet crude Cushing Oklahoma, acuan produk petrokimia global.",
    tanggalUpdate: "Hari ini",
    linkSumber: "https://www.tradingview.com/markets/commodities/prices/"
  },
  {
    id: 5,
    nama: "Batu Bara Newcastle",
    kategori: "Pasar Keuangan & Global",
    sumberData: "TradingView / Financial Market API",
    updateCadence: "Harian",
    hargaTerbaru: 138.50,
    mataUang: "USD",
    satuan: "ton",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: -0.65,
    statusRegulasi: "DMO PLN (Cap $70/ton pembangkit)",
    deskripsiSpesifikasi: "Kalori 6,000 kcal/kg GAR patokan ekspor dan pembangkit listrik tenaga uap.",
    tanggalUpdate: "Hari ini",
    linkSumber: "https://www.tradingview.com/markets/commodities/prices/"
  },
  {
    id: 6,
    nama: "Gas Alam (NYMEX)",
    kategori: "Pasar Keuangan & Global",
    sumberData: "TradingView / Financial Market API",
    updateCadence: "Harian",
    hargaTerbaru: 2.32,
    mataUang: "USD",
    satuan: "MMBtu",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 2.10,
    statusRegulasi: "HGBT Industri Tertentu ($6/MMBtu)",
    deskripsiSpesifikasi: "Bahan bakar gas pipa untuk industri pupuk, baja, dan kaca nasional.",
    tanggalUpdate: "Hari ini",
    linkSumber: "https://www.tradingview.com/markets/commodities/prices/"
  },
  {
    id: 7,
    nama: "CPO / Minyak Sawit Mentah",
    kategori: "Pasar Keuangan & Global",
    sumberData: "TradingView / Financial Market API",
    updateCadence: "Harian",
    hargaTerbaru: 3920.00,
    mataUang: "IDR",
    satuan: "kg (Rp 12.800/kg)",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.80,
    statusRegulasi: "Mandatori Biodiesel B35/B40 & DPO",
    deskripsiSpesifikasi: "Crude Palm Oil patokan lelang KPBN untuk pasokan minyak goreng dan oleokimia.",
    tanggalUpdate: "Hari ini",
    linkSumber: "https://www.tradingview.com/markets/commodities/prices/"
  },
  {
    id: 8,
    nama: "Gandum / Wheat (CME)",
    kategori: "Pasar Keuangan & Global",
    sumberData: "TradingView / Financial Market API",
    updateCadence: "Harian",
    hargaTerbaru: 5.75,
    mataUang: "USD",
    satuan: "bushel",
    jenisBatas: "Spot Global",
    perubahan24h: -0.40,
    statusRegulasi: "Bebas Bea Masuk Pangan Pokok Olahan",
    deskripsiSpesifikasi: "Bahan baku tepung terigu industri mie instan dan pakan ternak nasional.",
    tanggalUpdate: "Hari ini",
    linkSumber: "https://www.tradingview.com/markets/commodities/prices/"
  },
  {
    id: 9,
    nama: "Kedelai / Soybeans (CME)",
    kategori: "Pasar Keuangan & Global",
    sumberData: "TradingView / Financial Market API",
    updateCadence: "Harian",
    hargaTerbaru: 10.15,
    mataUang: "USD",
    satuan: "bushel",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.35,
    statusRegulasi: "Subsidi Selisih Harga Pengrajin Tahu-Tempe",
    deskripsiSpesifikasi: "Kedelai impor kuning No. 1/2 untuk konsumsi protein nabati rakyat.",
    tanggalUpdate: "Hari ini",
    linkSumber: "https://www.tradingview.com/markets/commodities/prices/"
  },
  {
    id: 10,
    nama: "Kakao / Cokelat (ICE)",
    kategori: "Pasar Keuangan & Global",
    sumberData: "TradingView / Financial Market API",
    updateCadence: "Harian",
    hargaTerbaru: 7650.00,
    mataUang: "USD",
    satuan: "ton",
    jenisBatas: "Spot Global",
    perubahan24h: 1.85,
    statusRegulasi: "Standar Ekspor Biji Kakao Fermentasi",
    deskripsiSpesifikasi: "Biji kakao kering petani untuk pengolahan bubuk dan mentega cokelat ekspor.",
    tanggalUpdate: "Hari ini",
    linkSumber: "https://www.tradingview.com/markets/commodities/prices/"
  },
  {
    id: 11,
    nama: "Kopi Robusta (ICE)",
    kategori: "Pasar Keuangan & Global",
    sumberData: "TradingView / Financial Market API",
    updateCadence: "Harian",
    hargaTerbaru: 4950.00,
    mataUang: "USD",
    satuan: "ton",
    jenisBatas: "Spot Global",
    perubahan24h: 1.20,
    statusRegulasi: "Harga Patokan Ekspor (HPE) Kemendag",
    deskripsiSpesifikasi: "Biji kopi robusta asalan Lampung/Bengkulu kadar air maksimal 13%.",
    tanggalUpdate: "Hari ini",
    linkSumber: "https://www.tradingview.com/markets/commodities/prices/"
  },
  {
    id: 12,
    nama: "Gula Mentah / Raw Sugar (ICE)",
    kategori: "Pasar Keuangan & Global",
    sumberData: "TradingView / Financial Market API",
    updateCadence: "Harian",
    hargaTerbaru: 21.80,
    mataUang: "USD",
    satuan: "cent/lb",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: -0.50,
    statusRegulasi: "Kuota Impor Industri Rafinasi",
    deskripsiSpesifikasi: "Gula mentah ICUMSA 600-1200 untuk pemurnian gula kristal konsumsi.",
    tanggalUpdate: "Hari ini",
    linkSumber: "https://www.tradingview.com/markets/commodities/prices/"
  },
  {
    id: 13,
    nama: "Tembaga / Copper (LME)",
    kategori: "Pasar Keuangan & Global",
    sumberData: "TradingView / Financial Market API",
    updateCadence: "Harian",
    hargaTerbaru: 9280.00,
    mataUang: "USD",
    satuan: "ton",
    jenisBatas: "Spot Global",
    perubahan24h: 0.70,
    statusRegulasi: "Wajib Hilirisasi Smelter Domestik",
    deskripsiSpesifikasi: "Katoda tembaga Grade A untuk kawat listrik kabel PLN dan motor listrik.",
    tanggalUpdate: "Hari ini",
    linkSumber: "https://www.tradingview.com/markets/commodities/prices/"
  },
  {
    id: 14,
    nama: "Aluminium (LME)",
    kategori: "Pasar Keuangan & Global",
    sumberData: "TradingView / Financial Market API",
    updateCadence: "Harian",
    hargaTerbaru: 2490.00,
    mataUang: "USD",
    satuan: "ton",
    jenisBatas: "Spot Global",
    perubahan24h: 0.15,
    statusRegulasi: "Larangan Ekspor Bauksit Mentah",
    deskripsiSpesifikasi: "Ingot aluminium kemurnian 99.7% untuk profil jendela dan otomotif.",
    tanggalUpdate: "Hari ini",
    linkSumber: "https://www.tradingview.com/markets/commodities/prices/"
  },
  {
    id: 15,
    nama: "Nikel / Nickel (LME)",
    kategori: "Pasar Keuangan & Global",
    sumberData: "TradingView / Financial Market API",
    updateCadence: "Harian",
    hargaTerbaru: 16150.00,
    mataUang: "USD",
    satuan: "ton",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: -1.10,
    statusRegulasi: "HPM Nikel Kementerian ESDM",
    deskripsiSpesifikasi: "Nikel MHP & Ferronickel untuk baja tahan karat (stainless) dan baterai EV.",
    tanggalUpdate: "Hari ini",
    linkSumber: "https://www.tradingview.com/markets/commodities/prices/"
  },
  {
    id: 16,
    nama: "Timah / Tin (LME/ICDX)",
    kategori: "Pasar Keuangan & Global",
    sumberData: "TradingView / Financial Market API",
    updateCadence: "Harian",
    hargaTerbaru: 31800.00,
    mataUang: "USD",
    satuan: "ton",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.45,
    statusRegulasi: "Wajib Transaksi Bursa ICDX / JFX",
    deskripsiSpesifikasi: "Balok timah murni 99.9% Bangka Belitung untuk solder elektronika global.",
    tanggalUpdate: "Hari ini",
    linkSumber: "https://www.tradingview.com/markets/commodities/prices/"
  },
  {
    id: 17,
    nama: "Besi Beton / Rebar (Dalian)",
    kategori: "Pasar Keuangan & Global",
    sumberData: "TradingView / Financial Market API",
    updateCadence: "Harian",
    hargaTerbaru: 3350.00,
    mataUang: "USD",
    satuan: "ton (CNY eq)",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: -0.30,
    statusRegulasi: "Standar SNI Wajib Konstruksi Nasional",
    deskripsiSpesifikasi: "Besi tulangan baja konstruksi gedung bertingkat dan jembatan.",
    tanggalUpdate: "Hari ini",
    linkSumber: "https://www.tradingview.com/markets/commodities/prices/"
  },
  {
    id: 18,
    nama: "Karet Alam (SGX/TOCOM)",
    kategori: "Pasar Keuangan & Global",
    sumberData: "TradingView / Financial Market API",
    updateCadence: "Harian",
    hargaTerbaru: 182.00,
    mataUang: "USD",
    satuan: "cent/kg",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.60,
    statusRegulasi: "Standar SIR 20 Petani Perkebunan",
    deskripsiSpesifikasi: "Karet bongkah TSR 20 bahan baku utama ban kendaraan bermotor.",
    tanggalUpdate: "Hari ini",
    linkSumber: "https://www.tradingview.com/markets/commodities/prices/"
  },
  {
    id: 19,
    nama: "Biji Besi / Iron Ore (SGX)",
    kategori: "Pasar Keuangan & Global",
    sumberData: "TradingView / Financial Market API",
    updateCadence: "Harian",
    hargaTerbaru: 94.20,
    mataUang: "USD",
    satuan: "dmt",
    jenisBatas: "Spot Global",
    perubahan24h: -0.85,
    statusRegulasi: "Patokan Blast Furnace Krakatau Steel",
    deskripsiSpesifikasi: "Konsentrat Fe 62% fines bahan pembuatan baja dasar batangan.",
    tanggalUpdate: "Hari ini",
    linkSumber: "https://www.tradingview.com/markets/commodities/prices/"
  },

  // 2. BAPANAS & PIHPS BANK INDONESIA (Pangan Pokok Lokal - Mingguan)
  {
    id: 20,
    nama: "Beras Premium",
    kategori: "Pangan Pokok Lokal",
    sumberData: "Kemendag SP2KP & SIMIRAH",
    updateCadence: "Mingguan",
    hargaTerbaru: 12500,
    mataUang: "IDR",
    satuan: "kg",
    jenisBatas: "HET Pemerintah",
    perubahan24h: 0.0,
    statusRegulasi: "HET Zonasi 1 Badan Pangan Nasional (Maks Rp 12.500)",
    deskripsiSpesifikasi: "Beras kualitas premium dengan derajat sosoh 100% dan butir patah maksimal 5%.",
    tanggalUpdate: "Pekan ini",
    linkSumber: "https://sp2kp.kemendag.go.id/statistik/tabulasi-harga"
  },
  {
    id: 21,
    nama: "Beras Medium",
    kategori: "Pangan Pokok Lokal",
    sumberData: "Kemendag SP2KP & SIMIRAH",
    updateCadence: "Mingguan",
    hargaTerbaru: 13450,
    mataUang: "IDR",
    satuan: "kg",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: -0.25,
    statusRegulasi: "HET Relaksasi Kemendag / Bapanas",
    deskripsiSpesifikasi: "Beras konsumsi umum derajat sosoh 95%, butir patah maksimal 20%.",
    tanggalUpdate: "Pekan ini",
    linkSumber: "https://sp2kp.kemendag.go.id/statistik/tabulasi-harga"
  },
  {
    id: 22,
    nama: "Gula Pasir Curah",
    kategori: "Pangan Pokok Lokal",
    sumberData: "Kemendag SP2KP & SIMIRAH",
    updateCadence: "Mingguan",
    hargaTerbaru: 17500,
    mataUang: "IDR",
    satuan: "kg",
    jenisBatas: "HET Pemerintah",
    perubahan24h: 0.0,
    statusRegulasi: "Harga Acuan Pembelian (HAP) Bapanas Rp 17.500/kg",
    deskripsiSpesifikasi: "Gula kristal putih (GKP) tebu konsumsi harian masyarakat.",
    tanggalUpdate: "Pekan ini",
    linkSumber: "https://sp2kp.kemendag.go.id/statistik/tabulasi-harga"
  },
  {
    id: 23,
    nama: "Telur Ayam Ras",
    kategori: "Pangan Pokok Lokal",
    sumberData: "Kemendag SP2KP & SIMIRAH",
    updateCadence: "Mingguan",
    hargaTerbaru: 28900,
    mataUang: "IDR",
    satuan: "kg",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.50,
    statusRegulasi: "HAP Bapanas Peternak Rp 22.000 - Rp 24.000",
    deskripsiSpesifikasi: "Telur segar ayam petelur (layer) curah ukuran sedang isi 16-17 butir.",
    tanggalUpdate: "Pekan ini",
    linkSumber: "https://sp2kp.kemendag.go.id/statistik/tabulasi-harga"
  },
  {
    id: 24,
    nama: "Daging Ayam Ras",
    kategori: "Pangan Pokok Lokal",
    sumberData: "Kemendag SP2KP & SIMIRAH",
    updateCadence: "Mingguan",
    hargaTerbaru: 36200,
    mataUang: "IDR",
    satuan: "kg",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: -0.80,
    statusRegulasi: "HAP Konsumen Bapanas Rp 36.750/kg",
    deskripsiSpesifikasi: "Karkas ayam broiler segar utuh tanpa jeroan dan cakar.",
    tanggalUpdate: "Pekan ini",
    linkSumber: "https://sp2kp.kemendag.go.id/statistik/tabulasi-harga"
  },
  {
    id: 25,
    nama: "Daging Sapi Impor Beku",
    kategori: "Pangan Pokok Lokal",
    sumberData: "Bapanas & PIHPS Bank Indonesia",
    updateCadence: "Mingguan",
    hargaTerbaru: 80000,
    mataUang: "IDR",
    satuan: "kg",
    jenisBatas: "HET Pemerintah",
    perubahan24h: 0.0,
    statusRegulasi: "HET Daging Kerbau/Sapi Beku Penugasan Bulog",
    deskripsiSpesifikasi: "Daging beku boneless kerbau India / sapi beku Australia operasi pasar.",
    tanggalUpdate: "Pekan ini",
    linkSumber: "https://panelharga.badanpangan.go.id/"
  },
  {
    id: 26,
    nama: "Daging Sapi Paha Belakang",
    kategori: "Pangan Pokok Lokal",
    sumberData: "Kemendag SP2KP & SIMIRAH",
    updateCadence: "Mingguan",
    hargaTerbaru: 134500,
    mataUang: "IDR",
    satuan: "kg",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.10,
    statusRegulasi: "HAP Bapanas Tingkat Konsumen",
    deskripsiSpesifikasi: "Daging sapi segar bagian paha belakang (Rump/Knuckle).",
    tanggalUpdate: "Pekan ini",
    linkSumber: "https://sp2kp.kemendag.go.id/statistik/tabulasi-harga"
  },
  {
    id: 27,
    nama: "Bawang Merah",
    kategori: "Pangan Pokok Lokal",
    sumberData: "Kemendag SP2KP & SIMIRAH",
    updateCadence: "Mingguan",
    hargaTerbaru: 31200,
    mataUang: "IDR",
    satuan: "kg",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: -1.25,
    statusRegulasi: "HAP Pembelian Petani Brebes/Nganjuk",
    deskripsiSpesifikasi: "Bawang merah rogol kering panen ukuran medium siap konsumsi.",
    tanggalUpdate: "Pekan ini",
    linkSumber: "https://sp2kp.kemendag.go.id/statistik/tabulasi-harga"
  },
  {
    id: 28,
    nama: "Bawang Putih Honan",
    kategori: "Pangan Pokok Lokal",
    sumberData: "Kemendag SP2KP & SIMIRAH",
    updateCadence: "Mingguan",
    hargaTerbaru: 39500,
    mataUang: "IDR",
    satuan: "kg",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.30,
    statusRegulasi: "Rekomendasi Impor Produk Hortikultura (RIPH)",
    deskripsiSpesifikasi: "Bawang putih impor kering kualitas standar konsumsi pasar induk.",
    tanggalUpdate: "Pekan ini",
    linkSumber: "https://sp2kp.kemendag.go.id/statistik/tabulasi-harga"
  },
  {
    id: 29,
    nama: "Cabai Rawit Merah",
    kategori: "Pangan Pokok Lokal",
    sumberData: "Kemendag SP2KP & SIMIRAH",
    updateCadence: "Mingguan",
    hargaTerbaru: 48500,
    mataUang: "IDR",
    satuan: "kg",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: -2.40,
    statusRegulasi: "HAP Petani & Konsumen Kemendag",
    deskripsiSpesifikasi: "Cabai rawit merah petik segar pedas tinggi komoditas penyumbang inflasi.",
    tanggalUpdate: "Pekan ini",
    linkSumber: "https://sp2kp.kemendag.go.id/statistik/tabulasi-harga"
  },
  {
    id: 30,
    nama: "Cabai Merah Keriting",
    kategori: "Pangan Pokok Lokal",
    sumberData: "Kemendag SP2KP & SIMIRAH",
    updateCadence: "Mingguan",
    hargaTerbaru: 42000,
    mataUang: "IDR",
    satuan: "kg",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 1.10,
    statusRegulasi: "HAP Fluktuasi Musim Hujan/Kemarau",
    deskripsiSpesifikasi: "Cabai keriting segar panjang untuk bumbu masak pokok rumah tangga.",
    tanggalUpdate: "Pekan ini",
    linkSumber: "https://sp2kp.kemendag.go.id/statistik/tabulasi-harga"
  },
  {
    id: 31,
    nama: "Ikan Kembung",
    kategori: "Pangan Pokok Lokal",
    sumberData: "Kemendag SP2KP & SIMIRAH",
    updateCadence: "Mingguan",
    hargaTerbaru: 37500,
    mataUang: "IDR",
    satuan: "kg",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.20,
    statusRegulasi: "Pantauan Protein Nelayan KKP",
    deskripsiSpesifikasi: "Ikan tangkap laut segar ukuran konsumsi rakyat kaya omega 3.",
    tanggalUpdate: "Pekan ini",
    linkSumber: "https://sp2kp.kemendag.go.id/statistik/tabulasi-harga"
  },
  {
    id: 32,
    nama: "Cabai Merah Besar",
    kategori: "Pangan Pokok Lokal",
    sumberData: "Kemendag SP2KP & SIMIRAH",
    updateCadence: "Mingguan",
    hargaTerbaru: 24500,
    mataUang: "IDR",
    satuan: "kg",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "Batas Bawah Peternak Kolam Terpal",
    deskripsiSpesifikasi: "Cabai merah besar segar, salah satu komoditas penyumbang inflasi pangan pokok.",
    tanggalUpdate: "Pekan ini",
    linkSumber: "https://sp2kp.kemendag.go.id/statistik/tabulasi-harga"
  },
  {
    id: 33,
    nama: "Pakan Ayam Ras / Broiler",
    kategori: "Pangan Pokok Lokal",
    sumberData: "Bapanas & PIHPS Bank Indonesia",
    updateCadence: "Mingguan",
    hargaTerbaru: 8800,
    mataUang: "IDR",
    satuan: "kg",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.15,
    statusRegulasi: "Standar Pabrik Pakan Ternak (Feedmill)",
    deskripsiSpesifikasi: "Pelet starter / finisher protein 20-22% penentu biaya pokok ayam.",
    tanggalUpdate: "Pekan ini",
    linkSumber: "https://panelharga.badanpangan.go.id/"
  },
  {
    id: 34,
    nama: "Bibit Ayam Usia Sehari (DOC)",
    kategori: "Pangan Pokok Lokal",
    sumberData: "Bapanas & PIHPS Bank Indonesia",
    updateCadence: "Mingguan",
    hargaTerbaru: 6500,
    mataUang: "IDR",
    satuan: "ekor",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: -0.75,
    statusRegulasi: "Penyesuaian Kuota Breeding Kementan",
    deskripsiSpesifikasi: "Day Old Chick (DOC) pedaging bibit unggul kualitas peternak mandiri.",
    tanggalUpdate: "Pekan ini",
    linkSumber: "https://panelharga.badanpangan.go.id/"
  },

  // 3. KEMENDAG SP2KP & SIMIRAH (Sembako & HET Pemerintah - Mingguan/Bulanan)
  {
    id: 35,
    nama: "Minyakita",
    kategori: "Sembako & HET Kemendag",
    sumberData: "Kemendag SP2KP & SIMIRAH",
    updateCadence: "Mingguan",
    hargaTerbaru: 15700,
    mataUang: "IDR",
    satuan: "liter (botol/bantal)",
    jenisBatas: "Subsidi",
    perubahan24h: 0.0,
    statusRegulasi: "HET Resmi Permendag No 18/2024 (Rp 15.700)",
    deskripsiSpesifikasi: "Minyak goreng sawit kemasan bantal/botol bersubsidi DMO pemerintah.",
    tanggalUpdate: "Pekan ini",
    linkSumber: "https://sp2kp.kemendag.go.id/statistik/tabulasi-harga"
  },
  {
    id: 36,
    nama: "Minyak Goreng Sawit Curah",
    kategori: "Sembako & HET Kemendag",
    sumberData: "Kemendag SP2KP & SIMIRAH",
    updateCadence: "Mingguan",
    hargaTerbaru: 14500,
    mataUang: "IDR",
    satuan: "liter",
    jenisBatas: "HET Pemerintah",
    perubahan24h: 0.0,
    statusRegulasi: "HET Batas Kemendag Rp 14.500 - 15.000",
    deskripsiSpesifikasi: "Minyak sawit curah tanpa kemasan untuk pedagang gorengan dan UMKM.",
    tanggalUpdate: "Pekan ini",
    linkSumber: "https://sp2kp.kemendag.go.id/statistik/tabulasi-harga"
  },
  {
    id: 37,
    nama: "Garam Halus",
    kategori: "Sembako & HET Kemendag",
    sumberData: "Kemendag SP2KP & SIMIRAH",
    updateCadence: "Bulanan",
    hargaTerbaru: 3000,
    mataUang: "IDR",
    satuan: "bungkus 250g",
    jenisBatas: "HET Pemerintah",
    perubahan24h: 0.0,
    statusRegulasi: "Standar Wajib Fortifikasi Yodium SNI 3556",
    deskripsiSpesifikasi: "Garam meja beryodium minimal 30 ppm pencegah stunting dan gondok.",
    tanggalUpdate: "Bulan ini",
    linkSumber: "https://sp2kp.kemendag.go.id/statistik/tabulasi-harga"
  },
  {
    id: 38,
    nama: "Tepung Terigu",
    kategori: "Sembako & HET Kemendag",
    sumberData: "Kemendag SP2KP & SIMIRAH",
    updateCadence: "Bulanan",
    hargaTerbaru: 10200,
    mataUang: "IDR",
    satuan: "kg",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "Standar SP2KP Bahan Pangan Pokok",
    deskripsiSpesifikasi: "Tepung terigu protein rendah/sedang curah bahan gorengan dan roti.",
    tanggalUpdate: "Bulan ini",
    linkSumber: "https://sp2kp.kemendag.go.id/statistik/tabulasi-harga"
  },
  {
    id: 39,
    nama: "Tahu Mentah",
    kategori: "Sembako & HET Kemendag",
    sumberData: "Kemendag SP2KP & SIMIRAH",
    updateCadence: "Mingguan",
    hargaTerbaru: 800,
    mataUang: "IDR",
    satuan: "potong (kotak)",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "Pantauan Koperasi Tahu Tempe (KOPTI)",
    deskripsiSpesifikasi: "Tahu putih basah ukuran standar 5x5 cm hasil olahan kedelai lokal/impor.",
    tanggalUpdate: "Pekan ini",
    linkSumber: "https://sp2kp.kemendag.go.id/"
  },
  {
    id: 40,
    nama: "Tempe Kedelai",
    kategori: "Sembako & HET Kemendag",
    sumberData: "Kemendag SP2KP & SIMIRAH",
    updateCadence: "Mingguan",
    hargaTerbaru: 6000,
    mataUang: "IDR",
    satuan: "papan (lonjor)",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "Pantauan KOPTI & BPS IHK",
    deskripsiSpesifikasi: "Tempe fermentasi ragi daun/plastik berat bersih 300-350 gram.",
    tanggalUpdate: "Pekan ini",
    linkSumber: "https://sp2kp.kemendag.go.id/"
  },
  {
    id: 41,
    nama: "Minyak Goreng Sawit Kemasan Premium",
    kategori: "Sembako & HET Kemendag",
    sumberData: "Kemendag SP2KP & SIMIRAH",
    updateCadence: "Bulanan",
    hargaTerbaru: 6000,
    mataUang: "IDR",
    satuan: "galon 19L",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "Standar Depot Air Minum Isi Ulang (DAMIU)",
    deskripsiSpesifikasi: "Minyak goreng kelapa sawit kemasan premium bermerek.",
    tanggalUpdate: "Bulan ini",
    linkSumber: "https://sp2kp.kemendag.go.id/statistik/tabulasi-harga"
  },
  {
    id: 42,
    nama: "Air Minum Galon Bermerek 19L",
    kategori: "Sembako & HET Kemendag",
    sumberData: "Kemendag SP2KP & SIMIRAH",
    updateCadence: "Bulanan",
    hargaTerbaru: 21000,
    mataUang: "IDR",
    satuan: "galon 19L (isi)",
    jenisBatas: "HET Pemerintah",
    perubahan24h: 0.0,
    statusRegulasi: "HET Acuan Pabrikan & Kemendag",
    deskripsiSpesifikasi: "Air mineral pegunungan botol polikarbonat bersegel resmi standar BPOM.",
    tanggalUpdate: "Bulan ini",
    linkSumber: "https://sp2kp.kemendag.go.id/"
  },
  {
    id: 43,
    nama: "Rokok Filter SKM (HET Cukai)",
    kategori: "Sembako & HET Kemendag",
    sumberData: "Kemendag SP2KP & SIMIRAH",
    updateCadence: "Bulanan",
    hargaTerbaru: 24500,
    mataUang: "IDR",
    satuan: "bungkus 12-16 btg",
    jenisBatas: "HET Pemerintah",
    perubahan24h: 0.0,
    statusRegulasi: "Harga Jual Eceran (HJE) PMK Tarif Cukai",
    deskripsiSpesifikasi: "Batas harga terendah pita cukai hasil tembakau golongan II SKM.",
    tanggalUpdate: "Bulan ini",
    linkSumber: "https://sp2kp.kemendag.go.id/"
  },
  {
    id: 44,
    nama: "Galon Air Minum Kosong 19L",
    kategori: "Sembako & HET Kemendag",
    sumberData: "Kemendag SP2KP & SIMIRAH",
    updateCadence: "Bulanan",
    hargaTerbaru: 38000,
    mataUang: "IDR",
    satuan: "unit fisik",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "Standar Food Grade SNI Plastik PET/PC",
    deskripsiSpesifikasi: "Galon wadah kosong standar industri air minum isi ulang dan pabrikan.",
    tanggalUpdate: "Bulan ini",
    linkSumber: "https://sp2kp.kemendag.go.id/"
  },

  // 4. KEMENTERIAN ESDM & PERTAMINA (Energi & Bahan Bakar Fisik - Mingguan/Kuartalan)
  {
    id: 45,
    nama: "Bensin Pertalite RON 90 (Subsidi)",
    kategori: "Energi & Bahan Bakar",
    sumberData: "Kementerian ESDM & Pertamina",
    updateCadence: "Mingguan",
    hargaTerbaru: 10000,
    mataUang: "IDR",
    satuan: "liter",
    jenisBatas: "Subsidi",
    perubahan24h: 0.0,
    statusRegulasi: "Jenis BBM Khusus Penugasan (JBKP) Kepmen ESDM",
    deskripsiSpesifikasi: "Bensin bersubsidi kuota APBN untuk kendaraan roda 2 dan angkutan umum.",
    tanggalUpdate: "Pekan ini",
    linkSumber: "https://mypertamina.id/fuels-harga"
  },
  {
    id: 46,
    nama: "Bensin Pertamax RON 92",
    kategori: "Energi & Bahan Bakar",
    sumberData: "Kementerian ESDM & Pertamina",
    updateCadence: "Bulanan",
    hargaTerbaru: 12950,
    mataUang: "IDR",
    satuan: "liter",
    jenisBatas: "HET Pemerintah",
    perubahan24h: 0.0,
    statusRegulasi: "BBM Umum Non-Subsidi Formulasi ESDM",
    deskripsiSpesifikasi: "Bahan bakar bensin oktan 92 ramah lingkungan untuk mesin injeksi modern.",
    tanggalUpdate: "Bulan ini",
    linkSumber: "https://mypertamina.id/fuels-harga"
  },
  {
    id: 47,
    nama: "Solar Subsidi / Bio Solar",
    kategori: "Energi & Bahan Bakar",
    sumberData: "Kementerian ESDM & Pertamina",
    updateCadence: "Mingguan",
    hargaTerbaru: 6800,
    mataUang: "IDR",
    satuan: "liter",
    jenisBatas: "Subsidi",
    perubahan24h: 0.0,
    statusRegulasi: "Jenis BBM Tertentu (JBT) Subsidi Tetap Rp 1.000/L",
    deskripsiSpesifikasi: "Bahan bakar mesin diesel campuran minyak sawit FAME 35% (B35).",
    tanggalUpdate: "Pekan ini",
    linkSumber: "https://mypertamina.id/fuels-harga"
  },
  {
    id: 48,
    nama: "Gas LPG 3 kg (Isi Subsidi)",
    kategori: "Energi & Bahan Bakar",
    sumberData: "Kementerian ESDM & Pertamina",
    updateCadence: "Mingguan",
    hargaTerbaru: 18000,
    mataUang: "IDR",
    satuan: "tabung (3kg)",
    jenisBatas: "Subsidi",
    perubahan24h: 0.0,
    statusRegulasi: "HET Pangkalan Resmi SK Gubernur (Rp 16.000 - 19.000)",
    deskripsiSpesifikasi: "Gas tabung melon bersubsidi terdaftar NIK KTP untuk rumah tangga miskin/UMKM.",
    tanggalUpdate: "Pekan ini",
    linkSumber: "https://mypertamina.id/fuels-harga"
  },
  {
    id: 49,
    nama: "Gas LPG 12 kg (Isi Standar)",
    kategori: "Energi & Bahan Bakar",
    sumberData: "Kementerian ESDM & Pertamina",
    updateCadence: "Bulanan",
    hargaTerbaru: 192000,
    mataUang: "IDR",
    satuan: "tabung (12kg)",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "Harga Agen Resmi Non-Subsidi Bright Gas",
    deskripsiSpesifikasi: "Refill gas cair elpiji 12 kg teknologi katup ganda (Double Spindle Valve).",
    tanggalUpdate: "Bulan ini",
    linkSumber: "https://mypertamina.id/fuels-harga"
  },
  {
    id: 50,
    nama: "Tabung Gas LPG 3 kg (Fisik Kosong)",
    kategori: "Energi & Bahan Bakar",
    sumberData: "Kementerian ESDM & Pertamina",
    updateCadence: "Kuartalan",
    hargaTerbaru: 125000,
    mataUang: "IDR",
    satuan: "unit tabung",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "Standar SNI 1452 Tabung Baja Bertekanan",
    deskripsiSpesifikasi: "Wadah fisik tabung baja hijau kapasitas 3 kg bersertifikat uji hidrostatik.",
    tanggalUpdate: "Kuartal ini",
    linkSumber: "https://mypertamina.id/fuels-harga"
  },
  {
    id: 51,
    nama: "Meteran PLN Prabayar (Fisik)",
    kategori: "Energi & Bahan Bakar",
    sumberData: "Kementerian ESDM & Pertamina",
    updateCadence: "Kuartalan",
    hargaTerbaru: 350000,
    mataUang: "IDR",
    satuan: "unit fisik",
    jenisBatas: "HET Pemerintah",
    perubahan24h: 0.0,
    statusRegulasi: "Biaya Sambung Pasang Baru Ditjen Ketenagalistrikan",
    deskripsiSpesifikasi: "kWh meter elektronik prabayar (token) 450-900 VA tarif bersubsidi.",
    tanggalUpdate: "Kuartal ini",
    linkSumber: "https://mypertamina.id/fuels-harga"
  },

  // 5. KEMENTERIAN PERTANIAN & PUPR (Pupuk Subsidi & Properti Fisik - Mingguan/Tahunan)
  {
    id: 52,
    nama: "Pupuk Urea Subsidi (HET)",
    kategori: "Pertanian & Properti Rakyat",
    sumberData: "Kementerian Pertanian & PUPR",
    updateCadence: "Mingguan",
    hargaTerbaru: 2250,
    mataUang: "IDR",
    satuan: "kg (Rp 112.500/sak 50kg)",
    jenisBatas: "Subsidi",
    perubahan24h: 0.0,
    statusRegulasi: "Permentan No 01/2024 tentang Alokasi & HET Pupuk",
    deskripsiSpesifikasi: "Pupuk nitrogen 46% prill warna merah muda bersubsidi e-RDKK petani.",
    tanggalUpdate: "Pekan ini",
    linkSumber: "https://psp.pertanian.go.id/"
  },
  {
    id: 53,
    nama: "Pupuk NPK Phonska Subsidi (HET)",
    kategori: "Pertanian & Properti Rakyat",
    sumberData: "Kementerian Pertanian & PUPR",
    updateCadence: "Mingguan",
    hargaTerbaru: 2300,
    mataUang: "IDR",
    satuan: "kg (Rp 115.000/sak 50kg)",
    jenisBatas: "Subsidi",
    perubahan24h: 0.0,
    statusRegulasi: "HET Pupuk Bersubsidi Resmi Kementan",
    deskripsiSpesifikasi: "Pupuk majemuk NPK 15-10-12 untuk tanaman pangan padi dan jagung rakyat.",
    tanggalUpdate: "Pekan ini",
    linkSumber: "https://psp.pertanian.go.id/"
  },
  {
    id: 54,
    nama: "Pupuk Organik Subsidi (HET)",
    kategori: "Pertanian & Properti Rakyat",
    sumberData: "Kementerian Pertanian & PUPR",
    updateCadence: "Mingguan",
    hargaTerbaru: 800,
    mataUang: "IDR",
    satuan: "kg (Rp 32.000/sak 40kg)",
    jenisBatas: "Subsidi",
    perubahan24h: 0.0,
    statusRegulasi: "HET Permentan Alokasi Tambahan Pupuk Organik",
    deskripsiSpesifikasi: "Pupuk kompos granul bahan alami penyubur struktur tanah sawah.",
    tanggalUpdate: "Pekan ini",
    linkSumber: "https://psp.pertanian.go.id/"
  },
  {
    id: 55,
    nama: "Pakan Ikan / Pelet",
    kategori: "Pertanian & Properti Rakyat",
    sumberData: "Kementerian Pertanian & PUPR",
    updateCadence: "Mingguan",
    hargaTerbaru: 11200,
    mataUang: "IDR",
    satuan: "kg",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "Program Gerpari (Gerakan Pakan Mandiri KKP)",
    deskripsiSpesifikasi: "Pelet apung protein 28-30% budidaya ikan lele, nila, dan gurami rakyat.",
    tanggalUpdate: "Pekan ini",
    linkSumber: "https://psp.pertanian.go.id/"
  },
  {
    id: 56,
    nama: "Rumah Subsidi Tipe 36 (Ceiling Gov)",
    kategori: "Pertanian & Properti Rakyat",
    sumberData: "Kementerian Pertanian & PUPR",
    updateCadence: "Tahunan",
    hargaTerbaru: 166000000,
    mataUang: "IDR",
    satuan: "unit rumah",
    jenisBatas: "Subsidi",
    perubahan24h: 0.0,
    statusRegulasi: "Kepmen PUPR Batas Maksimal Harga Rumah FLPP Zonasi Jawa",
    deskripsiSpesifikasi: "Rumah tapak sederhana luas bangunan 36m2 tanah 60m2 KPR subsidi FLPP bunga 5%.",
    tanggalUpdate: "Tahun ini",
    linkSumber: "https://psp.pertanian.go.id/"
  },
  {
    id: 57,
    nama: "Alat Semprot Pertanian 16L",
    kategori: "Pertanian & Properti Rakyat",
    sumberData: "Kementerian Pertanian & PUPR",
    updateCadence: "Kuartalan",
    hargaTerbaru: 245000,
    mataUang: "IDR",
    satuan: "unit sprayer",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "Standar e-Katalog Alsintan Kementan",
    deskripsiSpesifikasi: "Knapsack sprayer manual/elektrik tangki plastik 16 liter untuk semprot hama.",
    tanggalUpdate: "Kuartal ini",
    linkSumber: "https://psp.pertanian.go.id/"
  },
  {
    id: 58,
    nama: "Mesin Pompa Air Sawah 2 Inci",
    kategori: "Pertanian & Properti Rakyat",
    sumberData: "Kementerian Pertanian & PUPR",
    updateCadence: "Kuartalan",
    hargaTerbaru: 1450000,
    mataUang: "IDR",
    satuan: "unit mesin",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "Program Pompanisasi Lahan Kering Kementan",
    deskripsiSpesifikasi: "Pompa bensin 4-tak 5.5 HP pipa 2 inci irigasi darurat kekeringan sawah.",
    tanggalUpdate: "Kuartal ini",
    linkSumber: "https://psp.pertanian.go.id/"
  },
  {
    id: 59,
    nama: "Traktor Tangan Tani 2WD",
    kategori: "Pertanian & Properti Rakyat",
    sumberData: "Kementerian Pertanian & PUPR",
    updateCadence: "Tahunan",
    hargaTerbaru: 26500000,
    mataUang: "IDR",
    satuan: "unit traktor",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "Pengadaan Bantuan Alsintan Ditjen PSP",
    deskripsiSpesifikasi: "Hand tractor mesin diesel 8.5 HP bajak singkal pembajak lahan basah.",
    tanggalUpdate: "Tahun ini",
    linkSumber: "https://psp.pertanian.go.id/"
  },

  // 6. BPS / BADAN PUSAT STATISTIK (IHK, IHPB & Material Bangunan - Bulanan/Kuartalan)
  {
    id: 60,
    nama: "Mie Instan Sederhana",
    kategori: "IHK, Sandang & Material Bangunan",
    sumberData: "BPS / Badan Pusat Statistik",
    updateCadence: "Bulanan",
    hargaTerbaru: 3100,
    mataUang: "IDR",
    satuan: "bungkus 80g",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "Survei Biaya Hidup (SBH) IHK 90 Kota",
    deskripsiSpesifikasi: "Mie instan goreng/kuah rasa standar makanan penahan lapar jutaan keluarga.",
    tanggalUpdate: "Bulan ini",
    linkSumber: "https://www.bps.go.id/"
  },
  {
    id: 61,
    nama: "Susu Kental Manis Saset",
    kategori: "IHK, Sandang & Material Bangunan",
    sumberData: "BPS / Badan Pusat Statistik",
    updateCadence: "Bulanan",
    hargaTerbaru: 2500,
    mataUang: "IDR",
    satuan: "saset 37g",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "Indeks Harga Konsumen Kelompok Makanan Minuman",
    deskripsiSpesifikasi: "Krimer kental manis fortifikasi vitamin perisa vanila/cokelat.",
    tanggalUpdate: "Bulan ini",
    linkSumber: "https://www.bps.go.id/"
  },
  {
    id: 62,
    nama: "Susu Bubuk Balita Standard",
    kategori: "IHK, Sandang & Material Bangunan",
    sumberData: "BPS / Badan Pusat Statistik",
    updateCadence: "Bulanan",
    hargaTerbaru: 42000,
    mataUang: "IDR",
    satuan: "kotak 400g",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "Pantauan Nutrisi Anak Survei Sosial Ekonomi Nasional (Susenas)",
    deskripsiSpesifikasi: "Susu formula pertumbuhan anak 1-3 tahun zat besi dan DHA gizi balita.",
    tanggalUpdate: "Bulan ini",
    linkSumber: "https://www.bps.go.id/"
  },
  {
    id: 63,
    nama: "Kopi Bubuk Saset",
    kategori: "IHK, Sandang & Material Bangunan",
    sumberData: "BPS / Badan Pusat Statistik",
    updateCadence: "Bulanan",
    hargaTerbaru: 1500,
    mataUang: "IDR",
    satuan: "saset 25g",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "Paket Komoditas Dasar IHK BPS",
    deskripsiSpesifikasi: "Kopi hitam manis bubuk instan siap seduh warung kelontong.",
    tanggalUpdate: "Bulan ini",
    linkSumber: "https://www.bps.go.id/"
  },
  {
    id: 64,
    nama: "Detergen Bubuk Sederhana 800g",
    kategori: "IHK, Sandang & Material Bangunan",
    sumberData: "BPS / Badan Pusat Statistik",
    updateCadence: "Bulanan",
    hargaTerbaru: 17500,
    mataUang: "IDR",
    satuan: "kantong 800g",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "Indeks Konsumsi Perlengkapan Rumah Tangga",
    deskripsiSpesifikasi: "Deterjen pembersih pakaian konsentrat busa standar cuci harian.",
    tanggalUpdate: "Bulan ini",
    linkSumber: "https://www.bps.go.id/"
  },
  {
    id: 65,
    nama: "Sabun Mandi Batang",
    kategori: "IHK, Sandang & Material Bangunan",
    sumberData: "BPS / Badan Pusat Statistik",
    updateCadence: "Bulanan",
    hargaTerbaru: 3800,
    mataUang: "IDR",
    satuan: "batang 70g",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "Garis Kemiskinan Bukan Makanan BPS",
    deskripsiSpesifikasi: "Sabun mandi keluarga antibakteri ekstrak alami pembersih kulit.",
    tanggalUpdate: "Bulan ini",
    linkSumber: "https://www.bps.go.id/"
  },
  {
    id: 66,
    nama: "Pembalut Wanita Standar",
    kategori: "IHK, Sandang & Material Bangunan",
    sumberData: "BPS / Badan Pusat Statistik",
    updateCadence: "Bulanan",
    hargaTerbaru: 7500,
    mataUang: "IDR",
    satuan: "pak (isi 8-10 pads)",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "Komponen Sanitasi Esensial IHK",
    deskripsiSpesifikasi: "Pembalut bersayap higienis panjang 23 cm daya serap maksimal.",
    tanggalUpdate: "Bulan ini",
    linkSumber: "https://www.bps.go.id/"
  },
  {
    id: 67,
    nama: "Popok Bayi Sekali Pakai",
    kategori: "IHK, Sandang & Material Bangunan",
    sumberData: "BPS / Badan Pusat Statistik",
    updateCadence: "Bulanan",
    hargaTerbaru: 49000,
    mataUang: "IDR",
    satuan: "kantong M-34 / L-30",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "Survei Biaya Pengeluaran Rumah Tangga Balita",
    deskripsiSpesifikasi: "Diapers popok celana anti bocor sirkulasi udara kering 10 jam.",
    tanggalUpdate: "Bulan ini",
    linkSumber: "https://www.bps.go.id/"
  },
  {
    id: 68,
    nama: "Benang Jahit Katun",
    kategori: "IHK, Sandang & Material Bangunan",
    sumberData: "BPS / Badan Pusat Statistik",
    updateCadence: "Bulanan",
    hargaTerbaru: 2500,
    mataUang: "IDR",
    satuan: "gulung 500 yard",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "Survei IHPB Industri Tekstil & Konveksi",
    deskripsiSpesifikasi: "Benang spun polyester nomor 40/2 untuk jahit baju konveksi rumahan.",
    tanggalUpdate: "Bulan ini",
    linkSumber: "https://www.bps.go.id/"
  },
  {
    id: 69,
    nama: "Kain Katun Sederhana",
    kategori: "IHK, Sandang & Material Bangunan",
    sumberData: "BPS / Badan Pusat Statistik",
    updateCadence: "Bulanan",
    hargaTerbaru: 26000,
    mataUang: "IDR",
    satuan: "meter",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "Bahan Baku Pakaian Pokok IHK",
    deskripsiSpesifikasi: "Kain katun primisima / oxford lebar 115 cm serap keringat.",
    tanggalUpdate: "Bulan ini",
    linkSumber: "https://www.bps.go.id/"
  },
  {
    id: 70,
    nama: "Sepatu Sekolah Anak Hitam",
    kategori: "IHK, Sandang & Material Bangunan",
    sumberData: "BPS / Badan Pusat Statistik",
    updateCadence: "Kuartalan",
    hargaTerbaru: 78000,
    mataUang: "IDR",
    satuan: "pasang",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "Pantauan Perlengkapan Pendidikan Tahun Ajaran Baru",
    deskripsiSpesifikasi: "Sepatu kanvas hitam sol karet standar masuk sekolah negeri SD/SMP.",
    tanggalUpdate: "Kuartal ini",
    linkSumber: "https://www.bps.go.id/"
  },
  {
    id: 71,
    nama: "Seragam Sekolah SD Sederhana",
    kategori: "IHK, Sandang & Material Bangunan",
    sumberData: "BPS / Badan Pusat Statistik",
    updateCadence: "Kuartalan",
    hargaTerbaru: 65000,
    mataUang: "IDR",
    satuan: "setel (kemeja+celana/rok)",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "Pedoman Pakaian Seragam Sekolah Permendikbud",
    deskripsiSpesifikasi: "Setelan baju putih celana merah kain teteron katun anak usia sekolah.",
    tanggalUpdate: "Kuartal ini",
    linkSumber: "https://www.bps.go.id/"
  },
  {
    id: 72,
    nama: "Kaos Polos Katun",
    kategori: "IHK, Sandang & Material Bangunan",
    sumberData: "BPS / Badan Pusat Statistik",
    updateCadence: "Bulanan",
    hargaTerbaru: 28000,
    mataUang: "IDR",
    satuan: "potong",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "Komponen Pakaian Dewasa Garis Kemiskinan",
    deskripsiSpesifikasi: "T-shirt oblong katun combed 30s polos tanpa sablon.",
    tanggalUpdate: "Bulan ini",
    linkSumber: "https://www.bps.go.id/"
  },
  {
    id: 73,
    nama: "Semen PCC 50kg",
    kategori: "IHK, Sandang & Material Bangunan",
    sumberData: "BPS / Badan Pusat Statistik",
    updateCadence: "Bulanan",
    hargaTerbaru: 58000,
    mataUang: "IDR",
    satuan: "sak 50kg",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "IHPB Bahan Bangunan & e-Katalog LKPP",
    deskripsiSpesifikasi: "Semen Portland Composite Cement standar konstruksi plester dan cor.",
    tanggalUpdate: "Bulan ini",
    linkSumber: "https://www.bps.go.id/"
  },
  {
    id: 74,
    nama: "Pasir Pasang (per m3)",
    kategori: "IHK, Sandang & Material Bangunan",
    sumberData: "BPS / Badan Pusat Statistik",
    updateCadence: "Bulanan",
    hargaTerbaru: 240000,
    mataUang: "IDR",
    satuan: "m3",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "Standar Biaya Khusus (SBK) Pekerjaan Umum Dinas PUPR",
    deskripsiSpesifikasi: "Pasir tambang sungai ayak bebas lumpur untuk adukan pasangan bata.",
    tanggalUpdate: "Bulan ini",
    linkSumber: "https://www.bps.go.id/"
  },
  {
    id: 75,
    nama: "Batu Bata Merah",
    kategori: "IHK, Sandang & Material Bangunan",
    sumberData: "BPS / Badan Pusat Statistik",
    updateCadence: "Bulanan",
    hargaTerbaru: 750,
    mataUang: "IDR",
    satuan: "butir",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "IHPB Bahan Bangunan Tradisional",
    deskripsiSpesifikasi: "Bata tanah liat bakar lokal ukuran 19x9x4 cm dinding rumah tinggal.",
    tanggalUpdate: "Bulan ini",
    linkSumber: "https://www.bps.go.id/"
  },
  {
    id: 76,
    nama: "Batang Pipa PVC 3/4 Inci",
    kategori: "IHK, Sandang & Material Bangunan",
    sumberData: "BPS / Badan Pusat Statistik",
    updateCadence: "Bulanan",
    hargaTerbaru: 34000,
    mataUang: "IDR",
    satuan: "batang (4 meter)",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "Standar SNI Instalasi Saluran Air Bersih",
    deskripsiSpesifikasi: "Pipa paralon polivinil klorida tipe D/AW diameter 3/4 inci instalasi air.",
    tanggalUpdate: "Bulan ini",
    linkSumber: "https://www.bps.go.id/"
  },
  {
    id: 77,
    nama: "Seng Gelombang / Atap Asbes",
    kategori: "IHK, Sandang & Material Bangunan",
    sumberData: "BPS / Badan Pusat Statistik",
    updateCadence: "Bulanan",
    hargaTerbaru: 68000,
    mataUang: "IDR",
    satuan: "lembar (1.8m)",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "IHPB Komponen Penutup Atap",
    deskripsiSpesifikasi: "Atap seng galvalum gelombang tebal 0.25 mm tahan karat sederhana.",
    tanggalUpdate: "Bulan ini",
    linkSumber: "https://www.bps.go.id/"
  },
  {
    id: 78,
    nama: "Kayu Balok Borneo/Lokal",
    kategori: "IHK, Sandang & Material Bangunan",
    sumberData: "BPS / Badan Pusat Statistik",
    updateCadence: "Bulanan",
    hargaTerbaru: 2450000,
    mataUang: "IDR",
    satuan: "m3",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "Verifikasi Legalitas Kayu (SVLK) KLHK",
    deskripsiSpesifikasi: "Kayu reng/kaso lokal ukuran 5x7 cm atau balok 6x12 cm rangka plafon.",
    tanggalUpdate: "Bulan ini",
    linkSumber: "https://www.bps.go.id/"
  },
  {
    id: 79,
    nama: "Batang Baja WF / Wide Flange",
    kategori: "IHK, Sandang & Material Bangunan",
    sumberData: "BPS / Badan Pusat Statistik",
    updateCadence: "Bulanan",
    hargaTerbaru: 14200,
    mataUang: "IDR",
    satuan: "kg (Rp 1.420.000/btg)",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "Standar Konstruksi Baja Struktur Tahan Gempa",
    deskripsiSpesifikasi: "Profil baja struktural I-beam / H-beam pabrikan rangka gudang dan jembatan.",
    tanggalUpdate: "Bulan ini",
    linkSumber: "https://www.bps.go.id/"
  },
  {
    id: 80,
    nama: "Cat Tembok Interior 5kg",
    kategori: "IHK, Sandang & Material Bangunan",
    sumberData: "BPS / Badan Pusat Statistik",
    updateCadence: "Bulanan",
    hargaTerbaru: 78000,
    mataUang: "IDR",
    satuan: "galon 5kg",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "IHPB Bahan Pelapis Finishing",
    deskripsiSpesifikasi: "Cat emulsi akrilik dinding dalam ruangan warna putih cerah ramah bau.",
    tanggalUpdate: "Bulan ini",
    linkSumber: "https://www.bps.go.id/"
  },
  {
    id: 81,
    nama: "Keramik Lantai 30x30 Polos",
    kategori: "IHK, Sandang & Material Bangunan",
    sumberData: "BPS / Badan Pusat Statistik",
    updateCadence: "Bulanan",
    hargaTerbaru: 46000,
    mataUang: "IDR",
    satuan: "dus (1 m2)",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "Standar Lantai Rumah Sederhana Sehat PUPR",
    deskripsiSpesifikasi: "Ubin keramik glasir putih polos kilap (glossy) isi 11 keping per dus.",
    tanggalUpdate: "Bulan ini",
    linkSumber: "https://www.bps.go.id/"
  },
  {
    id: 82,
    nama: "Aspal Hotmix (per ton)",
    kategori: "IHK, Sandang & Material Bangunan",
    sumberData: "BPS / Badan Pusat Statistik",
    updateCadence: "Kuartalan",
    hargaTerbaru: 1250000,
    mataUang: "IDR",
    satuan: "ton",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "Spesifikasi Bina Marga Divisi 6 Perkerasan Aspal",
    deskripsiSpesifikasi: "Campuran aspal panas AC-WC (Asphalt Concrete Wearing Course) pelapis jalan.",
    tanggalUpdate: "Kuartal ini",
    linkSumber: "https://www.bps.go.id/"
  },
  {
    id: 83,
    nama: "Helm Motor SNI Open Face",
    kategori: "IHK, Sandang & Material Bangunan",
    sumberData: "BPS / Badan Pusat Statistik",
    updateCadence: "Kuartalan",
    hargaTerbaru: 110000,
    mataUang: "IDR",
    satuan: "unit",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "Wajib SNI 1811 Perlindungan Pengendara Korlantas",
    deskripsiSpesifikasi: "Pelindung kepala busa EPS bersertifikat keselamatan lalu lintas jalan.",
    tanggalUpdate: "Kuartal ini",
    linkSumber: "https://www.bps.go.id/"
  },

  // 7. KEMENKES (HET Obat Generik - Bulanan)
  {
    id: 84,
    nama: "Obat Parasetamol Generik 500mg",
    kategori: "Kesehatan & Obat Generik",
    sumberData: "Kemenkes (HET Obat Generik)",
    updateCadence: "Bulanan",
    hargaTerbaru: 3500,
    mataUang: "IDR",
    satuan: "strip (10 tablet)",
    jenisBatas: "HET Pemerintah",
    perubahan24h: 0.0,
    statusRegulasi: "Kepmenkes HET Obat Generik Esensial (Rp 350/tablet)",
    deskripsiSpesifikasi: "Analgesik & antipiretik penurun panas demam dan pereda nyeri dasar.",
    tanggalUpdate: "Bulan ini",
    linkSumber: "https://farmalkes.kemkes.go.id/"
  },
  {
    id: 85,
    nama: "Obat Amoksisilin Generik 500mg",
    kategori: "Kesehatan & Obat Generik",
    sumberData: "Kemenkes (HET Obat Generik)",
    updateCadence: "Bulanan",
    hargaTerbaru: 6000,
    mataUang: "IDR",
    satuan: "strip (10 kaplet)",
    jenisBatas: "HET Pemerintah",
    perubahan24h: 0.0,
    statusRegulasi: "HET Kemenkes Obat Keras Resep Dokter",
    deskripsiSpesifikasi: "Antibiotik spektrum luas infeksi bakteri saluran pernapasan.",
    tanggalUpdate: "Bulan ini",
    linkSumber: "https://farmalkes.kemkes.go.id/"
  },
  {
    id: 86,
    nama: "Antasida Doen Generik",
    kategori: "Kesehatan & Obat Generik",
    sumberData: "Kemenkes (HET Obat Generik)",
    updateCadence: "Bulanan",
    hargaTerbaru: 3000,
    mataUang: "IDR",
    satuan: "strip (10 tab kunyah)",
    jenisBatas: "HET Pemerintah",
    perubahan24h: 0.0,
    statusRegulasi: "Daftar Obat Esensial Nasional (DOEN)",
    deskripsiSpesifikasi: "Aluminium & magnesium hidroksida penetral asam lambung maag.",
    tanggalUpdate: "Bulan ini",
    linkSumber: "https://farmalkes.kemkes.go.id/"
  },
  {
    id: 87,
    nama: "Vitamin C 500mg Generik",
    kategori: "Kesehatan & Obat Generik",
    sumberData: "Kemenkes (HET Obat Generik)",
    updateCadence: "Bulanan",
    hargaTerbaru: 4500,
    mataUang: "IDR",
    satuan: "strip (10 tablet)",
    jenisBatas: "HET Pemerintah",
    perubahan24h: 0.0,
    statusRegulasi: "Pedoman HET Suplemen Daya Tahan Tubuh Kemenkes",
    deskripsiSpesifikasi: "Asam askorbat tablet salut suplemen imunitas pencegah sariawan.",
    tanggalUpdate: "Bulan ini",
    linkSumber: "https://farmalkes.kemkes.go.id/"
  },

  // 8. E-COMMERCE / MARKETPLACE SCRAPER (Barang Konsumen & Otomotif - Bulanan/Kuartalan)
  {
    id: 88,
    nama: "Lampu LED Rumah 10W",
    kategori: "Konsumen & Otomotif",
    sumberData: "E-Commerce / Marketplace Scraper",
    updateCadence: "Bulanan",
    hargaTerbaru: 14500,
    mataUang: "IDR",
    satuan: "bohlam",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: -0.50,
    statusRegulasi: "Standar Efisiensi Energi Label Bintang ESDM",
    deskripsiSpesifikasi: "Bohlam LED fitting E27 hemat energi 900 lumens cahaya putih sejuk.",
    tanggalUpdate: "Bulan ini",
    linkSumber: "https://www.tokopedia.com/"
  },
  {
    id: 89,
    nama: "Kertas HVS A4 70g",
    kategori: "Konsumen & Otomotif",
    sumberData: "E-Commerce / Marketplace Scraper",
    updateCadence: "Bulanan",
    hargaTerbaru: 41000,
    mataUang: "IDR",
    satuan: "rim (500 lembar)",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "Standar Kebutuhan Administrasi Perkantoran & Sekolah",
    deskripsiSpesifikasi: "Kertas fotokopi putih derajat putih 98% bebas macet printer.",
    tanggalUpdate: "Bulan ini",
    linkSumber: "https://www.tokopedia.com/"
  },
  {
    id: 90,
    nama: "Oli Mesin Motor Matik 10W-40 (0.8L)",
    kategori: "Konsumen & Otomotif",
    sumberData: "E-Commerce / Marketplace Scraper",
    updateCadence: "Bulanan",
    hargaTerbaru: 44000,
    mataUang: "IDR",
    satuan: "botol 800ml",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "Standar Sertifikasi Mutu JASO MB / API SL",
    deskripsiSpesifikasi: "Pelumas mesin matic sintetis perlindungan gesekan motor roda dua.",
    tanggalUpdate: "Bulan ini",
    linkSumber: "https://www.tokopedia.com/"
  },
  {
    id: 91,
    nama: "Ban Motor Tubeless Ring 14",
    kategori: "Konsumen & Otomotif",
    sumberData: "E-Commerce / Marketplace Scraper",
    updateCadence: "Kuartalan",
    hargaTerbaru: 155000,
    mataUang: "IDR",
    satuan: "unit (80/90-14)",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "Wajib SNI Keselamatan Roda Kendaraan Bermotor",
    deskripsiSpesifikasi: "Ban luar tubeless kompon medium cengkeraman jalan basah/kering.",
    tanggalUpdate: "Kuartal ini",
    linkSumber: "https://www.tokopedia.com/"
  },
  {
    id: 92,
    nama: "Aki Motor 12V 3.5Ah",
    kategori: "Konsumen & Otomotif",
    sumberData: "E-Commerce / Marketplace Scraper",
    updateCadence: "Kuartalan",
    hargaTerbaru: 165000,
    mataUang: "IDR",
    satuan: "unit aki kering",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "Standar Baterai Starter Kering Maintenance Free (MF)",
    deskripsiSpesifikasi: "Aki bebas perawatan motor matik 110-125cc siap pasang starter.",
    tanggalUpdate: "Kuartal ini",
    linkSumber: "https://www.tokopedia.com/"
  },
  {
    id: 93,
    nama: "Sepeda Motor Matik 110cc (Harga OTR Terendah)",
    kategori: "Konsumen & Otomotif",
    sumberData: "E-Commerce / Marketplace Scraper",
    updateCadence: "Kuartalan",
    hargaTerbaru: 18500000,
    mataUang: "IDR",
    satuan: "unit motor OTR",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "Harga On The Road Resmi Agen Tunggal Pemegang Merek (ATPM)",
    deskripsiSpesifikasi: "Motor skutik entry-level 110cc injeksi eSP/Blue Core konsumsi 60km/liter.",
    tanggalUpdate: "Kuartal ini",
    linkSumber: "https://www.tokopedia.com/"
  },
  {
    id: 94,
    nama: "Sepeda Listrik Entry-Level",
    kategori: "Konsumen & Otomotif",
    sumberData: "E-Commerce / Marketplace Scraper",
    updateCadence: "Kuartalan",
    hargaTerbaru: 3450000,
    mataUang: "IDR",
    satuan: "unit e-bike",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: -1.00,
    statusRegulasi: "Permenhub No 45/2020 tentang Kendaraan Tertentu Motor Listrik",
    deskripsiSpesifikasi: "E-bike baterai 48V 12Ah motor 500W jarak tempuh 40 km kecepatan maks 25 km/jam.",
    tanggalUpdate: "Kuartal ini",
    linkSumber: "https://www.tokopedia.com/"
  },
  {
    id: 95,
    nama: "Mobil Pick-Up Bak Open 1.5L",
    kategori: "Konsumen & Otomotif",
    sumberData: "E-Commerce / Marketplace Scraper",
    updateCadence: "Kuartalan",
    hargaTerbaru: 162000000,
    mataUang: "IDR",
    satuan: "unit OTR",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "Pajak Kendaraan Niaga UMKM & Angkutan Barang",
    deskripsiSpesifikasi: "Kendaraan niaga bak terbuka daya angkut 1 ton andalan logistik pasar.",
    tanggalUpdate: "Kuartal ini",
    linkSumber: "https://www.tokopedia.com/"
  },
  {
    id: 96,
    nama: "Kasur Busa Single 90x200",
    kategori: "Konsumen & Otomotif",
    sumberData: "E-Commerce / Marketplace Scraper",
    updateCadence: "Kuartalan",
    hargaTerbaru: 295000,
    mataUang: "IDR",
    satuan: "unit kasur",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "Perlengkapan Kamar Tidur Dasar Susenas BPS",
    deskripsiSpesifikasi: "Matras busa polyurethane tebal 14 cm bungkus kain katun bermotif.",
    tanggalUpdate: "Kuartal ini",
    linkSumber: "https://www.tokopedia.com/"
  },
  {
    id: 97,
    nama: "Kipas Angin Stand Fan 16 Inci",
    kategori: "Konsumen & Otomotif",
    sumberData: "E-Commerce / Marketplace Scraper",
    updateCadence: "Kuartalan",
    hargaTerbaru: 155000,
    mataUang: "IDR",
    satuan: "unit",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "Wajib SNI Keselamatan Motor Elektrik Rumah Tangga",
    deskripsiSpesifikasi: "Kipas berdiri baling-baling 16 inci daya 45W dengan osilasi 90 derajat.",
    tanggalUpdate: "Kuartal ini",
    linkSumber: "https://www.tokopedia.com/"
  },
  {
    id: 98,
    nama: "Mesin Pemotong Rumput 2-Tak",
    kategori: "Konsumen & Otomotif",
    sumberData: "E-Commerce / Marketplace Scraper",
    updateCadence: "Kuartalan",
    hargaTerbaru: 780000,
    mataUang: "IDR",
    satuan: "unit mesin",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "Alat Kebersihan Lingkungan & Perkebunan",
    deskripsiSpesifikasi: "Brush cutter gendong silinder 30.5cc pisau baja pembersih semak liar.",
    tanggalUpdate: "Kuartal ini",
    linkSumber: "https://www.tokopedia.com/"
  },

  // 9. LOCAL UTILITIES & INSTITUTIONS (Fisik Pendukung - Kuartalan/Tahunan)
  {
    id: 99,
    nama: "Meteran Air PDAM (Fisik)",
    kategori: "Fasilitas Utilitas Publik",
    sumberData: "Local Utilities & Institutions",
    updateCadence: "Kuartalan",
    hargaTerbaru: 220000,
    mataUang: "IDR",
    satuan: "unit meter air",
    jenisBatas: "HET Pemerintah",
    perubahan24h: 0.0,
    statusRegulasi: "Standar Tera Metrologi Legal & SK Direksi PDAM Daerah",
    deskripsiSpesifikasi: "Water meter kuningan anti korosi 1/2 inci kelas B akurasi pengukuran debit air.",
    tanggalUpdate: "Kuartal ini",
    linkSumber: "https://data.go.id/"
  },

  // 10. MANUAL INPUT / FIELD SURVEI (1% Data Manual)
  {
    id: 100,
    nama: "Jasa Tukang Bangunan Harian (Batas Standar)",
    kategori: "Tenaga Kerja & Jasa Konstruksi",
    sumberData: "Manual Input / Field Survei",
    updateCadence: "Bulanan",
    hargaTerbaru: 135000,
    mataUang: "IDR",
    satuan: "hari kerja (8 jam)",
    jenisBatas: "Batas Terendah / Floor",
    perubahan24h: 0.0,
    statusRegulasi: "Upah Minimum Sektoral / Standar Analisa Harga Satuan Pekerjaan (AHSP)",
    deskripsiSpesifikasi: "Upah harian tukang batu/kayu terampil di luar uang makan dan mandor proyek.",
    tanggalUpdate: "Bulan ini",
    linkSumber: "https://www.bi.go.id/hargapangan/"
  }
];

export const COMMODITY_SOURCES = [
  "TradingView / Financial Market API",
  "Bapanas & PIHPS Bank Indonesia",
  "Kemendag SP2KP & SIMIRAH",
  "Kementerian ESDM & Pertamina",
  "Kementerian Pertanian & PUPR",
  "BPS / Badan Pusat Statistik",
  "Kemenkes (HET Obat Generik)",
  "E-Commerce / Marketplace Scraper",
  "Local Utilities & Institutions",
  "Manual Input / Field Survei"
];

export const UPDATE_CADENCES: UpdateCadence[] = [
  "Harian",
  "Mingguan",
  "Bulanan",
  "Kuartalan",
  "Tahunan"
];

export const PRICING_TYPES: PricingType[] = [
  "Subsidi",
  "HET Pemerintah",
  "Batas Terendah / Floor",
  "Spot Global"
];
